### ISSUE TITLE
Crash upon launching the game

### ISSUE THREAD

**Issue by nthgava** [Engine-Room/Flywheel#103]
### Describe the Bug

Crash upon launching the game with Flywheel 0.6.0

### Reproduction Steps

1. Launch game using flywheel 0.6.0
2. Crash

### Expected Result

Expected outcome is for the game to launch, to see the title screen and then play the game

### Crash Report or Log

https://pastebin.com/wnsMThXF

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1050

### Mod Version

0.5.1

### Minecraft Version

1.18.1

### Forge Version

39.0.59

### Other Mods

Seen in the crash report, notably the Create mod's latest version

### Additional Context

****NOTE: Flywheel version is 0.6.0, not 0.5.1, the option for 0.6.0 was not given in the crash report

**Comment by Jozufozu** [comment]
According to the crash report you *are* using Flywheel 0.5.1
