### ISSUE TITLE
Crash on Startup - Cannot read field "name" because "spec" is null

### ISSUE THREAD

**Issue by PhiliaHalls** [Engine-Room/Flywheel#105]
Crash report here - https://pastebin.com/Zcxp89Kk

Currently running Java 17.0.2 and tried running on various forge versions from 39.0.59 to 39.0.48.

**Comment by emihead** [comment]
Why was this closed? I'm getting the same crash.
Edit: Nevermind, forgot about the Curseforge app bug that keeps old versions when you update.
