### ISSUE TITLE
Game crashing due to Flywheel? (Unexpected error java.lang.ExceptionInInitializerError)

### ISSUE THREAD

**Issue by TobySushi** [Engine-Room/Flywheel#106]
So, I've been having some issues with flywheel in which it causes my game to crash whenever an object from the create mod is loaded in-game. I've taken multiple steps to get this issue to stop happening, but I can't seem to make any progress.
1. I've tried downgrading the mod and create to older versions
2. I've tried using multiple versions of forge
3. I've tried removing mods like optifine that have caused issues in the past

The only thing that will "fix" the problem is disabling flywheel and create, which removes the objects from the world. The only issue is that once I go back and place those objects back in, they cause the same crash to happen.
Attached is a relevant crash log.
I've been downloading all of the mods through curse forge, but I'm unsure if that has anything to do with the aforementioned bug
[crash-2022-01-29_01.19.32-client.txt](https://github.com/Jozufozu/Flywheel/files/7963127/crash-2022-01-29_01.19.32-client.txt)
.

**Comment by Jozufozu** [comment]
Use [this version of starlight](https://www.curseforge.com/minecraft/mc-mods/starlight-forge/files/3599856).
