### ISSUE TITLE
Crash - Placing Shulker Chest in the End

### ISSUE THREAD

**Issue by VieLassiel** [Engine-Room/Flywheel#109]
### Describe the Bug

While roaming the end the client will randomly crash.
From what I can tell it's a render issue with Flywheel.

EDIT: It seems to happen every time when placing down a shulker chest while in the End.

### Reproduction Steps

1. Roam around the End.
2. Place down a shulker chest in the End.

The crash is consistent when placing down a shulker chest while in the End.

### Expected Result

I expected to not crash? Lol this section is silly sometimes.

### Crash Report or Log

https://pastebin.com/BkkNuXf3

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1070

### Mod Version

0.6.0

### Minecraft Version

1.18.1

### Forge Version

39.0.64

### Other Mods

[OptiFine HD U H4](https://www.optifine.net/downloads)

[CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Create Deco](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Gravestone mod](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)
[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Areas (Forge)](https://www.curseforge.com/minecraft/mc-mods/areas)
[Balm (Forge Edition)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Better Compatibility Checker](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[Cable Tiers](https://www.curseforge.com/minecraft/mc-mods/cable-tiers)
[Cloth Config API (Forge)](https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge)
[Collective (Forge)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Craftable Horse Armour & Saddle [CHA&S]](https://www.curseforge.com/minecraft/mc-mods/cha-s)
[Crafting Tweaks](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks)
[Create](https://www.curseforge.com/minecraft/mc-mods/create)
[Create Crafts & Additions](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Cucumber Library](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[Curious API (Forge)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Ding](https://www.curseforge.com/minecraft/mc-mods/ding)
[Easier Sleeping](https://www.curseforge.com/minecraft/mc-mods/easier-sleeping)
[ExtraStorage](https://www.curseforge.com/minecraft/mc-mods/extrastorage)
[Falling Tree (Forge&Fabric)](https://www.curseforge.com/minecraft/mc-mods/falling-tree)
[Flywheel](https://www.curseforge.com/minecraft/mc-mods/flywheel)
[Forgiving Void](https://www.curseforge.com/minecraft/mc-mods/forgiving-void)
[GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[GoProne](https://www.curseforge.com/minecraft/mc-mods/goprone)
[Hand Over Your Items (Forge)](https://www.curseforge.com/minecraft/mc-mods/hand-over-your-items)
[Immersive Engineering](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
[Iron Chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Iron Jetpacks](https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks)
[JEITweaker](https://www.curseforge.com/minecraft/mc-mods/jeitweaker)
[Just Enough Items (JEI)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Login Protection [Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/login-protection)
[Mana and Artifice](https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice)
[Measurements](https://www.curseforge.com/minecraft/mc-mods/measurements)
[Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Move Boats (Forge)](https://www.curseforge.com/minecraft/mc-mods/move-boats)
[Move Minecarts (Forge)](https://www.curseforge.com/minecraft/mc-mods/move-minecarts)
[Not Enough Crashes (Forge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[OAuth](https://www.curseforge.com/minecraft/mc-mods/oauth)
[OpenBlocks Elevator](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Packing Tape](https://www.curseforge.com/minecraft/mc-mods/packing-tape)
[Ping](https://www.curseforge.com/minecraft/mc-mods/ping)
[Pipez](https://www.curseforge.com/minecraft/mc-mods/pipez)
[Placebo](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Polymorph (Forge)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Potions Master](https://www.curseforge.com/minecraft/mc-mods/potionsmaster)
[Refined Storage](https://www.curseforge.com/minecraft/mc-mods/refined-storage)
[Refined Storage: Requestify](https://www.curseforge.com/minecraft/mc-mods/rs-requestify)
[Roots Classic](https://www.curseforge.com/minecraft/mc-mods/roots-classic)
[Set World Spawn Point (Forge)](https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point)
[Simply Light](https://www.curseforge.com/minecraft/mc-mods/simply-light)
[Sleeping Bags](https://www.curseforge.com/minecraft/mc-mods/sleeping-bags)
[Spice of Life: Carroy Edition](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition)
[Stronger Farmland](https://www.curseforge.com/minecraft/mc-mods/stronger-farmland)
[SwingThroughGrass](https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass)
[The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)
[Torch Slabs Mod](https://www.curseforge.com/minecraft/mc-mods/torchslabs-mod)
[Torchmaster](https://www.curseforge.com/minecraft/mc-mods/torchmaster)

**Comment by VieLassiel** [comment]
Seems to happen every time when placing a Shulker Chest down while in the end.

**Comment by LautjeDS** [comment]
Happend to me aswell.

**Comment by ddthejj** [comment]
this also happens with regular chests, also while roaming the end in modded you can run into chunks with chests / shulker chests in them so I think that's what was causing the issue initially

**Comment by twothe** [comment]
Randomly crashing in the end, makes playing impossible.

**Comment by CDAGaming** [comment]
Having this same issue as wel
[hs_err_pid9092.log](https://github.com/Jozufozu/Flywheel/files/8145566/hs_err_pid9092.log)
l

**Comment by Jozufozu** [comment]
Fixed in latest flywheel
