### ISSUE TITLE
"Flywheel Not Installed"

### ISSUE THREAD

**Issue by Dev001L** [Engine-Room/Flywheel#11]
"Flywheel not Installed"... that word scare me....... lol! Anyway, im having a problem in download of Create Mod that required Flywheel, but i already install the FW. I tried over and over and dont work, the problem is the version required (Flywheel 1.6-0.1) i tried ALL of them and dont work.

**Comment by NighthowlerStudios** [comment]
install create 0.3.2b specifically

**Comment by Dev001L** [comment]
> install create 0.3.2b specifically

I try this, but i dont know what version to install
