### ISSUE TITLE
Unexpected error and game crash

### ISSUE THREAD

**Issue by namuistree00** [Engine-Room/Flywheel#112]
### Describe the Bug

If I install the block of create while the game is in progress, the game will be broken.
I solved it.
When I deleted the starlight mod, it worked fine.

### Reproduction Steps

1. I placed a mixer in the world.
2. and crash
3. After that, i can't access the world.

### Expected Result

Not to crash

### Crash Report or Log

https://pastebin.com/Pykwz61w

### Operating System

windows 10

### What is your GPU?

NVIDIA GeForce GTX 1060

### Mod Version

0.6.0

### Minecraft Version

1.18.1

### Forge Version

39.0.76

### Other Mods

many mods

**Comment by Jozufozu** [comment]
Update starlight
