### ISSUE TITLE
G1Exception: Could not map buffer -> game crashes

### ISSUE THREAD

**Issue by HeyImKyu** [Engine-Room/Flywheel#113]
### Describe the Bug

Game crashes ~5 seconds after joining world in the End.
Playing ATM7 with version 0.2.41
Flywheel version is 0.6.0

### Reproduction Steps

Do not know exactly, but for me, it's just loading into the world while in the end.
Happened first when getting shot by a shulker.

### Expected Result

No crash.

### Crash Report or Log

https://pastebin.com/PuukSKWz

### Operating System

Windows 11

### What is your GPU?

GTX 1070

### Mod Version

0.6.0

### Minecraft Version

1.18.1

### Forge Version

39.0.75

### Other Mods

ATM7 Modpack

**Comment by grundyboy34** [comment]
Same issue here. Log looks the same.
