### ISSUE TITLE
Consistent Crash on Startup (direct after loading screen - 1.18.2) 

### ISSUE THREAD

**Issue by newcron** [Engine-Room/Flywheel#119]
### Describe the Bug

When I add forge to the mods directory and start minecraft with the forge launcher, I don't get beyond the red "Mojang" loading screen. At the moment, the progress bar reaches the end, the game exits. 

To my understanding (when looking at the exception stack traces, this has nothing to do with drivers, as there's a couple no NoClassDefFound Errors) 

### Reproduction Steps

1. Minecraft Java Edition 1.182 with forge 1.18.2 - 40.0.19
2. put forge into the mods directory
3. start using Microsoft Minecraft Launcher
4. app will consistently crash after the Mojang loading screen

### Expected Result

I'd expect minecraft to start normally

### Crash Report or Log

https://pastebin.com/MF6vY1xM

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 2080 TI

### Mod Version

0.6.2

### Minecraft Version

1.18.1

### Forge Version

40.0.19

### Other Mods

No other mods running

**Comment by PepperCode1** [comment]
Create does not have a 1.18.2 release yet.
