### ISSUE TITLE
[fabric] Full jvm crash with batching backend

### ISSUE THREAD

**Issue by redstonerti** [Engine-Room/Flywheel#122]
### Describe the Bug

Gantry carriages moving cause minecraft to crash
![image](https://user-images.githubusercontent.com/48157961/160258895-957a2525-4a40-42a6-98a5-0af0e743ba24.png)
It also reverted the world probably due to the nature of the crash

### Reproduction Steps

Place a gantry shaft and a gantry carriage on it. Move them. Experience a full JVM crash

### Expected Result

I expected the gantry carriage to move

### Operating System

Windows 10

### What is your GPU?

Gtx 1070

### Mod Version

0.6.2

### Minecraft Version

1.18.1

### Forge Version

Fabric 0.13.3-1.18.1

### Additional Context

The mod version is wrong. I don't know the version because I'm using create on fabric build 445

**Comment by PepperCode1** [comment]
0.6.2 is the 1.18.2 version. There is no way you would be able to start Minecraft 1.18.1 with this version due to its dependency declaration. Please send a crash log so this issue can be debugged.
