### ISSUE TITLE
Rendering crash.

### ISSUE THREAD

**Issue by border999** [Engine-Room/Flywheel#125]
### Describe the Bug

Crash on startup.

### Reproduction Steps

https://gist.github.com/border999/ab4df7fc69bf6cf302b8ee1a8b23dea1

### Expected Result

not crash

### Crash Report or Log

https://gist.github.com/border999/ab4df7fc69bf6cf302b8ee1a8b23dea1

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 1080

### Mod Version

0.6.2

1.18.2

Forge 40.0.52

### Similar issues found.

https://github.com/Asek3/Radium/issues/20
https://github.com/Creators-of-Create/Create/issues/2987

**Comment by Jozufozu** [comment]
This looks like a crash loading vanilla shaders modified in a resource pack
