### ISSUE TITLE
ShaderLoadingException

### ISSUE THREAD

**Issue by Devalut** [Engine-Room/Flywheel#126]
### Describe the Bug

What version do I need to launch the game?
Attached shows the error message when trying a different version of fly wheel.
Each error message points to another and it's seems unplayable.
And any reports regarding this issue are either closed with no solution or solved with a version that is outdated.

Using the latest ones for 1.1.6.5 results in this crash:
`com.jozufozu.flywheel.backend.loading.ShaderLoadingException: Could not load all shaders, see log for details
`
Full log:
https://pastebin.com/7d3BUwkJ

### Reproduction Steps

1.Fresh install of 3.2G create and listed versions of flywheel below
 
### Expected Result

A goose chase of versions.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/20247202/163741295-855e31b0-6df3-45b1-b12b-d3ae64925b04.png)

![image](https://user-images.githubusercontent.com/20247202/163740857-0aed7090-0614-4d7c-a2d7-5b8e84fbba65.png)

![image](https://user-images.githubusercontent.com/20247202/163740801-73820780-04bc-4960-834c-a321684f112c.png)

![image](https://user-images.githubusercontent.com/20247202/163741166-e458f6d3-7998-4394-a617-5eae9d777f48.png)

![image](https://user-images.githubusercontent.com/20247202/163741087-c58fcb66-29fa-4c96-90cd-3397b68c1565.png)

![image](https://user-images.githubusercontent.com/20247202/163741009-2b5315b3-6680-4787-99cd-d0c23a3c459b.png)

![image](https://user-images.githubusercontent.com/20247202/163740957-049e247a-fb58-413b-8d0a-2ec36fa0c5e5.png)

![image](https://user-images.githubusercontent.com/20247202/163740626-7d86db38-8b4e-4dd3-a546-e013c3a2425c.png)

### Operating System

Windows 7

### Mod Version

0.3.2g create & Attached versions of flywheel

### Minecraft Version

1.16.5

### Forge Version

36.2.20 with java 1.8.0_311 & 36.2.33 with lastest Java

**Comment by Jozufozu** [comment]
Not sure how I can help. The pastebin log says you're using flywheel 0.2.5. Please update to the latest versions of create and flywheel if you can
