### ISSUE TITLE
Game crashed when trying to play with pistons for create mod - error message invovles flywheel

### ISSUE THREAD

**Issue by TriangledMilk** [Engine-Room/Flywheel#128]
### Describe the Bug

When I was playing with the create mod, especially with the pistons, I put down a piston shaft because I was trying to figure out the mod more. But then when I connected it to a running gear shaft it crashed.

### Reproduction Steps

1. Have a gearshaft connected to a running waterwheel in the create mod. 
2. Have a piston with piston shaft under it near by, with the piston having a wool block on top of it.
3. Connect the running gear shaft to the piston with a shaft, you should get a crash
...

### Expected Result

I was expecting the piston to extend. 

### Crash Report or Log

https://pastebin.com/yP1nGAYR

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3060

### Mod Version

0.4.0

### Minecraft Version

1.18

### Loader Version

Forge 38.0.17

**Comment by ImHoppy** [comment]
Hi,
I can't reproduce the crash on my side.
Have testing with newer version like 0.4a?
If your problem persists, can you post an issue in the [Create ](https://github.com/Creators-of-Create/Create/)repository?
[Here](https://github.com/Creators-of-Create/Create/issues/new?assignees=&labels=bug&template=bug_report.yml)

![This is an image](https://i.imgur.com/Aw3fhSg.png)

**Comment by Jozufozu** [comment]
This is fixed already, please update if you can
