### ISSUE TITLE
Shadows render from the wrong direction with Optifine shaders

### ISSUE THREAD

**Issue by TLATER** [Engine-Room/Flywheel#13]
I recently updated my create version, which introduced this flywheel dependency.

I'm not 100% sure the problem comes from here, but given that this seems to be a rendering overhaul partially targeting that mod, I think it's at least a good place to start :) Do tell if I should move this elsewhere.

I've only seen fallout from moving create objects so far, if there are other things I could look at to help pin down the issue, please ask!

## Context

After an update of create that includes the flywheel dependency, shadows on moving create objects now seem to render from the wrong direction when using optifine shaders.

### Mods

- Flywheel 0.2.0
- Create 0.3.2c
- OptiFine HD U G8

### Tested Shaders

- [Sildur's Vibrant shaders v1.29 Extreme-Volumetric lighting](https://sildurs-shaders.github.io/)
- [BSL v8.1 preview 1](https://bitslablab.com/bslshaders/#download)

## Screenshots

It's somewhat hard to accurately represent the issue. Instead of logs (since those have no interesting info, I'll happily provide logs if asked, though), I think screenshots do better here.

I hope it's somewhat clear that in the "before" screenshot the shadows appear neatly behind the sail frames, on the windmill body, whereas in the "after" they appear on the ground/building before me. Shadows seem to vaguely be relative to the player.

The shadows also move with in the inverse direction of the camera, which makes this effect a whole lot more jarring than it may seem.

These screenshots are both from a very modded version of the game, since I only have the given screenshot of the old version; if you'd like me to produce comparison screenshots with a clean environment, I'll happily do so, but this is a bit easier right now - I *have* reproduced it with the listed mods isolated :)

### Before (Create/Flywheel <= 0.3.2b/0.1.1)

![2021-05-04_00 40 27](https://user-images.githubusercontent.com/6654841/127723914-a3af4a18-fae8-42f7-9ea1-0cf94924f0ef.png)

### After (Create/Flywheel == 0.3.2c/0.2.0)

![2021-07-31_02 12 53](https://user-images.githubusercontent.com/6654841/127724050-3ce5b74c-6eae-4d76-bd20-de96c247d7e0.png)

## Video

I uploaded a short video to youtube in a test world with just the above mods installed, where i'm flying around a windmill to showcase the issue: https://youtu.be/J0dX10QfUmw

**Comment by Duorhs** [comment]
I got the same issue, and after standing a few second my game even crashed...Here is my log
https://github.com/Creators-of-Create/Create/issues/2064

**Comment by TLATER** [comment]
@Duorhs I had a crash like that too, but it was likely caused by using the wrong version of selene with supplementaries. I've not seen it since fixing that, with a few hours of playtime.

You seem to have a lot of other mods installed, I think that crash is a red herring and unrelated to this - try and isolate out _just_ the mods causing the behavior, it's nigh impossible to debug otherwise :)

**Comment by Duorhs** [comment]
> @Duorhs I had a crash like that too, but it was likely caused by using the wrong version of selene with supplementaries. I've not seen it since fixing that, with a few hours of playtime.
> 
> You seem to have a lot of other mods installed, I think that crash is a red herring and unrelated to this - try and isolate out _just_ the mods causing the behavior, it's nigh impossible to debug otherwise :)

thx for reply, indeed I play with a lot of mods. But the crash started today after I update : Create & Flywheel , Thermal series , Better foliage.

**Comment by Duorhs** [comment]
> @Duorhs I had a crash like that too, but it was likely caused by using the wrong version of selene with supplementaries. I've not seen it since fixing that, with a few hours of playtime.
> 
> You seem to have a lot of other mods installed, I think that crash is a red herring and unrelated to this - try and isolate out _just_ the mods causing the behavior, it's nigh impossible to debug otherwise :)

Thanks for reply , I play with a lot of mods , but everything is fine until I update Create & Flywheel , Thermal Series and Better Foliage and CraftTweaker today. However, my game crashed after it loaded so the world was saved with these newer version mods. I tried to  start a new game , it didn't crash . But downgrading these mods and load the old world will be another type of crash. So I can't ioslate it with my old world...

**Comment by TLATER** [comment]
@Duorhs You've not tried everything yet!

The error seems related to create's belts - read the first line of your error log ;) So maybe you need to have placed at least one of those.

If that's not enough to isolate the mods, try the following:

1. Create a backup of your world (!), and never open this one directly
2. Create a copy of your backup
3. Disable *all* mods, except create + flywheel
4. Start the game and enter that copy
5. Play until you see your crash
6. If no crash occurs, repeat steps 2-6, except enable another mod you suspect in step 2
  - In your case, try these mods in order:
    - Thermal Series
    - Better Foliage
    - CraftTweaker
    - Optifine
    - Any other mods you have
7. Whenever you do get a crash, start the game with just create, flywheel and the mod you just enabled

You'll eventually reproduce your issue :) The trick is keeping an untouched copy of your world, so that your mods can screw up however much they like.

Once you have isolated the mods causing the issue, create a new issue with those. I doubt it will be related to this issue, though the error message does suggest that create is involved. Don't think shaders care much about the block facing direction, so optifine is likely not the culprit.

If this seems like a lot of effort, yes, it is!

The reason this is important is because the mod authors would have to go through *exactly* this procedure to figure out what's going on anyway, but they don't even know what mods you're running. Even if they did, it's a long process and they have more important things to look at, even if they're doing this full-time and as paid work. So do your part and help produce an exact reproduction scenario - it's an open source project after all, contribute what you can if you want something improved!

If you can only reproduce it in your existing world, you may even need to upload a copy of it.

Anyway, all of this discussion is irrelevant to this particular issue, so feel free to continue it on Creators-of-Create/Create#2064.

**Comment by Duorhs** [comment]
> @Duorhs You've not tried everything yet!
> 
> The error seems related to create's belts - read the first line of your error log ;) So maybe you need to have placed at least one of those.
> 
> If that's not enough to isolate the mods, try the following:
> 
> 1. Create a backup of your world (!), and never open this one directly
> 2. Create a copy of your backup
> 3. Disable _all_ mods, except create + flywheel
> 4. Start the game and enter that copy
> 5. Play until you see your crash
> 6. If no crash occurs, repeat steps 2-6, except enable another mod you suspect in step 2
> 
> * In your case, try these mods in order:
>   
>   * Thermal Series
>   * Better Foliage
>   * CraftTweaker
>   * Optifine
>   * Any other mods you have
> 
> 1. Whenever you do get a crash, start the game with just create, flywheel and the mod you just enabled
> 
> You'll eventually reproduce your issue :) The trick is keeping an untouched copy of your world, so that your mods can screw up however much they like.
> 
> Once you have isolated the mods causing the issue, create a new issue with those. I doubt it will be related to this issue, though the error message does suggest that create is involved. Don't think shaders care much about the block facing direction, so optifine is likely not the culprit.
> 
> If this seems like a lot of effort, yes, it is!
> 
> The reason this is important is because the mod authors would have to go through _exactly_ this procedure to figure out what's going on anyway, but they don't even know what mods you're running. Even if they did, it's a long process and they have more important things to look at, even if they're doing this full-time and as paid work. So do your part and help produce an exact reproduction scenario - it's an open source project after all, contribute what you can if you want something improved!
> 
> If you can only reproduce it in your existing world, you may even need to upload a copy of it.
> 
> Anyway, all of this discussion is irrelevant to this particular issue, so feel free to continue it on [Creators-of-Create/Create#2064](https://github.com/Creators-of-Create/Create/issues/2064).

Thanks a lot, this gives me clear and simple ideas to figure out the problem, I'll find time to try it out!

**Comment by Duorhs** [comment]
While I was doing some work to test, I noticed that my issus in Create has been addressed. I built the mod with the latest code and it didn't crash (by Create) any more...However the shadow issue as this topic mentioned at first is still there.

**Comment by Jozufozu** [comment]
Fixed in latest create/flywheel, this was a weird one for sure

**Comment by TLATER** [comment]
Thanks!
