### ISSUE TITLE
Flywheel fakeplayer api issue

### ISSUE THREAD

**Issue by papuSpartan** [Engine-Room/Flywheel#133]
### Describe the Bug

Create mod crashes my server due to an issue with flywheel's fake player api. 
See [this github issue](https://github.com/FabricMC/fabric/issues/1980) for more detail (given to me by dev of caller further up stacktrace).

### Reproduction Steps

1. join server
2. place Create mod deployer block for the first time
3. get achievement from placing block
4. server crashes immediately after step 3
...

### Expected Result

Server continues to run as normal

### Screenshots and Videos

[Kyori lib's interaction with Flywheel](https://imgur.com/a/9K6L8Tc)

### Crash Report or Log

https://pastebin.com/HmzE1ABz

### Operating System

Linux, Windows 10, Windows 11

### What is your GPU?

Nvidia Geforce 980 Ti

### Mod Version

0.6.2

### Minecraft Version

1.18.1

### Loader Version

Fabric 0.14.6

### Additional Context

See [https://github.com/FabricMC/fabric/issues/1980](https://github.com/FabricMC/fabric/issues/1980)

**Comment by TropheusJ** [comment]
remove better-fabric-console, and this is completely unrelated to flywheel.

**Comment by papuSpartan** [comment]
@TropheusJ what's wrong with better-fabric-console?

**Comment by TropheusJ** [comment]
that's what uses adventure-platform-fabric, which causes the crash.

**Comment by papuSpartan** [comment]
@TropheusJ I didn't realize that fabric crash logs provided a more verbose listing of mod internal libraries. Thank you, will mark as closed.

**Comment by itsdinkd** [comment]
Instead of removing mods, wouldn't fixing the issue at hand would be better? Maybe work with FAPI on getting a Fake Player API going so we don't have 20 something mods fighting each other

**Comment by TropheusJ** [comment]
It’s not an issue we can fix, it has to be handled by one of our dependencies and has already been reported.

**Comment by itsdinkd** [comment]
This makes me sad :(

**Comment by itsdinkd** [comment]
Tech just got back to the issue opened on FAPI so maybe they'll implement... maybe.. If they did, would create be willing to use Fabric Api's version?

**Comment by TropheusJ** [comment]
Yes
