### ISSUE TITLE
Crashed when Shader enabled and did not do /flywheel backend off create mod

### ISSUE THREAD

**Issue by Nygosaki** [Engine-Room/Flywheel#135]
### Describe the Bug

Game crashes when Shaders are enabled and I haven't done /flywheel backend off yet.

### Reproduction Steps

1. Install create
2. Install shaders
3. Go into world
4. Enable shaders
5. Place down a create piston
6. Crashed

If we would add a step before placing down the piston of doing the /flywheel backend off command game will not crash

### Expected Result

Game shouldn't crash

### Crash Report or Log

https://pastebin.com/bp8G5901

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3080 Max-Q

### Mod Version

0.6.2

### Minecraft Version

1.18.1

### Loader Version

Forge 40.1.51

### Other Mods

	Mod List: 
		rsrequestify-2.2.0.jar                            |RSRequestify                  |rsrequestify                  |2.2.0               |DONE      |Manifest: NOSIGNATURE
		dynamiclightsreforged-1.18.2_v1.3.3.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.18.2_v1.3.3       |DONE      |Manifest: NOSIGNATURE
		CyclopsCore-1.18.2-1.15.1.jar                     |Cyclops Core                  |cyclopscore                   |1.15.1              |DONE      |Manifest: NOSIGNATURE
		TreeChop-1.18.2-0.15.7.jar                        |HT's TreeChop                 |treechop                      |0.15.7              |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.18.2-Forge-1.0.jar         |YUNG's Better Witch Huts      |betterwitchhuts               |1.18.2-Forge-1.0    |DONE      |Manifest: NOSIGNATURE
		bigbrain-1.5.3.jar                                |Big Brain                     |bigbrain                      |1.5.3               |DONE      |Manifest: NOSIGNATURE
		cftlc-1.0.1+1.18.2.jar                            |Creatures from the Lush Cave  |cftlc                         |1.0.1               |DONE      |Manifest: NOSIGNATURE
		AdditionalEnchanting1.6(1.18.2).jar               |Additional Enchanting         |additional_enchanting         |1.0.0               |DONE      |Manifest: NOSIGNATURE
		refinedpipes-0.6.2.jar                            |Refined Pipes                 |refinedpipes                  |0.6.2               |DONE      |Manifest: NOSIGNATURE
		IntegratedTerminals-1.18.2-1.3.0.jar              |IntegratedTerminals           |integratedterminals           |1.3.0               |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.18.2-2.5.0.jar                     |Doggy Talents 2               |doggytalents                  |2.5.0               |DONE      |Manifest: NOSIGNATURE
		autooredictconv-1.18.2-18.0.2.jar                 |Auto Ore Dictionary Converter |autooredictconv               |18.0.2              |DONE      |Manifest: NOSIGNATURE
		torohealth-1.18-forge-2.jar                       |ToroHealth                    |torohealth                    |1.18-forge-2        |DONE      |Manifest: NOSIGNATURE
		Incendium_v5.0.4.jar                              |Incendium                     |incendium                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.2a.jar                               |Rubidium                      |rubidium                      |0.5.2a              |DONE      |Manifest: NOSIGNATURE
		kleeslabs-forge-1.18.2-11.1.1.jar                 |KleeSlabs                     |kleeslabs                     |11.1.1              |DONE      |Manifest: NOSIGNATURE
		noautojump-1.18.2-1.jar                           |No Auto-Jump                  |noautojump                    |1.18.2-1            |DONE      |Manifest: NOSIGNATURE
		InsaneLib-1.5.1-mc1.18.2.jar                      |InsaneLib                     |insanelib                     |1.5.1               |DONE      |Manifest: NOSIGNATURE
		Neat 1.8-30.jar                                   |Neat                          |neat                          |1.8-30              |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+19.jar               |Controlling                   |controlling                   |9.0+19              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.2-6.4.0.jar                          |Placebo                       |placebo                       |6.4.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.18.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.5              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.0.8.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.0.8  |DONE      |Manifest: NOSIGNATURE
		finsandtails-1.18.2-1.0.1.jar                     |Fins and Tails                |finsandtails                  |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |2.0.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
		mdecore-1.18.2-18.0.1.jar                         |MattDahEpic Core              |mdecore                       |18.0.1              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.2.21.jar                |Bookshelf                     |bookshelf                     |13.2.21             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.18.2.1.4.3.jar                   |Guard Villagers               |guardvillagers                |1.4.3               |DONE      |Manifest: NOSIGNATURE
		ProgressiveBosses-3.5.14-mc1.18.2.jar             |Progressive Bosses            |progressivebosses             |3.5.14              |DONE      |Manifest: NOSIGNATURE
		Rex's-AdditionalStructures-1.18.2-(v.3.1.0).jar   |Additional Structures         |additionalstructures          |3.1.0               |DONE      |Manifest: NOSIGNATURE
		carrynametag-1.0-1.18.jar                         |Carry the Nametag             |carrynametag                  |1.0-1.18            |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.18.2-10.2.4.464.jar          |Mekanism: Generators          |mekanismgenerators            |10.2.4              |DONE      |Manifest: NOSIGNATURE
		balm-3.1.0+0.jar                                  |Balm                          |balm                          |3.1.0+0             |DONE      |Manifest: NOSIGNATURE
		immersive_armors-1.3.5.jar                        |Immersive Armors              |immersive_armors              |1.3.5               |DONE      |Manifest: NOSIGNATURE
		FpsReducer2-forge-1.18.2-2.0.jar                  |FPS Reducer                   |fpsreducer                    |1.18.2-2.0          |DONE      |Manifest: NOSIGNATURE
		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE
		BetterThanMending-1.7.1.jar                       |BetterThanMending             |betterthanmending             |1.7.1               |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.2.62-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.62              |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.2-1.0.6.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.2-1.0.6        |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.10.2.jar                         |Refined Storage               |refinedstorage                |1.10.2              |DONE      |Manifest: NOSIGNATURE
		corpse-1.18.2-1.0.1.jar                           |Corpse                        |corpse                        |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		endlessocean-1.18.2-0.2.5-BETA.jar                |Endless Ocean Aquatic Adventur|endlessocean                  |0.2.5-BETA          |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.18.2-3.3.1.3-7.jar         |Industrial Foregoing          |industrialforegoing           |3.3.1.3             |DONE      |Manifest: NOSIGNATURE
		DustrialDecor-1.3.3-1.18.2.jar                    |'Dustrial Decor               |dustrial_decor                |1.3.2               |DONE      |Manifest: NOSIGNATURE
		Amplified_Nether_v1.1.1.jar                       |Amplified Nether              |amplifiednether               |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-5.1.14+1.18.2.jar     |Repurposed Structures         |repurposed_structures         |5.1.14+1.18.2       |DONE      |Manifest: NOSIGNATURE
		morevillagers-forge-1.18.2-3.3.1.jar              |More Villagers                |morevillagers                 |3.3.1               |DONE      |Manifest: NOSIGNATURE
		curious-armor-stands-1.18.1-4.0.0.jar             |Curious Armor Stands          |curious_armor_stands          |1.18.1-4.0.0        |DONE      |Manifest: NOSIGNATURE
		CommonCapabilities-1.18.2-2.8.2.jar               |CommonCapabilities            |commoncapabilities            |2.8.2               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.109-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.109   |DONE      |Manifest: NOSIGNATURE
		1.18.2-enchantedgoldenapplecrafting-1.0.jar       |Enchanted Golden Apple Craftin|enchantedgoldenapplecrafting  |1.0                 |DONE      |Manifest: NOSIGNATURE
		projectvibrantjourneys-1.18.2-4.0.0-ALPHA6.jar    |Project Vibrant Journeys      |projectvibrantjourneys        |1.18.2-4.0.0-ALPHA6 |DONE      |Manifest: NOSIGNATURE
		endrem_forge-5.1.0-R-1.18.2.jar                   |End Remastered                |endrem                        |5.1.0-R-1.18.2      |DONE      |Manifest: NOSIGNATURE
		YungsBridges-1.18.2-Forge-2.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		simplylight-1.18.2-1.4.2-build.31.jar             |Simply Light                  |simplylight                   |1.18.2-1.4.2-build.3|DONE      |Manifest: NOSIGNATURE
		enchantmenttransfer-0.0.4-1.18.2.jar              |Enchantment Transfer          |enchantmenttransfer           |0.0.4               |DONE      |Manifest: NOSIGNATURE
		spark-1.9.11-forge.jar                            |spark                         |spark                         |1.9.11              |DONE      |Manifest: NOSIGNATURE
		simplybackpacks-1.18.2-2.1.2-build.40.jar         |Simply Backpacks              |simplybackpacks               |1.18.2-2.1.2-build.4|DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.0.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-70.jar                           |Patchouli                     |patchouli                     |1.18.2-70           |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.18.2-1.2.5.jar                         |Oculus                        |oculus                        |1.2.5               |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-4.28.jar                        |Collective                    |collective                    |4.28                |DONE      |Manifest: NOSIGNATURE
		camera-1.18.2-1.0.2.jar                           |Camera Mod                    |camera                        |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		AppleTreesRev-Forge-1.18.2-v2.0.jar               |Apple Trees Rev.              |appletreesrev                 |2.0                 |DONE      |Manifest: NOSIGNATURE
		TreePlant-1.18.2-0.3.0.jar                        |HT's TreePlant                |treeplant                     |0.3.0               |DONE      |Manifest: NOSIGNATURE
		torch-bandolier-1.18.2-1.8.0.jar                  |Torch Bandolier               |torchbandolier                |1.8.0               |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.18.2-Forge-2.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		IntegratedTunnels-1.18.2-1.8.12.jar               |IntegratedTunnels             |integratedtunnels             |1.8.12              |DONE      |Manifest: NOSIGNATURE
		BetterVillage-Forge-1.18.2-1.0.1.jar              |Better Village                |bettervillage                 |1                   |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18.2-1.8.1.jar          |Better Third Person           |betterthirdperson             |1.8.1               |DONE      |Manifest: NOSIGNATURE
		Chunk Pregenerator-1.18-4.0.2.jar                 |Chunk Pregenerator            |chunkpregen                   |1.18-4.0.2          |DONE      |Manifest: NOSIGNATURE
		passiveshield_1.18.2-2.0.jar                      |Passive Shield                |passiveshield                 |2.0                 |DONE      |Manifest: NOSIGNATURE
		Runelic-Forge-1.18.2-11.0.1.jar                   |Runelic                       |runelic                       |11.0.1              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MekanismTools-1.18.2-10.2.4.464.jar               |Mekanism: Tools               |mekanismtools                 |10.2.4              |DONE      |Manifest: NOSIGNATURE
		architectury-4.5.74-forge.jar                     |Architectury                  |architectury                  |4.5.74              |DONE      |Manifest: NOSIGNATURE
		moreoverlays-1.20.5-mc1.18.1.jar                  |More Overlays Updated         |moreoverlays                  |1.20.5-mc1.18.1     |DONE      |Manifest: NOSIGNATURE
		light-overlay-6.0.5-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.5               |DONE      |Manifest: NOSIGNATURE
		ItemPhysic_v1.4.23_mc1.18.2.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |Manifest: NOSIGNATURE
		InvMoveCompats-1.18-0.1.0-Forge.jar               |InvMove Compat                |invmove_compat                |0.1.0               |DONE      |Manifest: NOSIGNATURE
		glowinc-1.18.2_1.2.3.jar                          |Glow Inc.                     |glowinc                       |1.18.2_1.2.3        |DONE      |Manifest: NOSIGNATURE
		JadeAddons-1.18.2-2.0.0.jar                       |Jade Addons                   |jadeaddons                    |2.0.0               |DONE      |Manifest: NOSIGNATURE
		inventoryessentials-forge-1.18.2-4.0.2.jar        |Inventory Essentials          |inventoryessentials           |4.0.2               |DONE      |Manifest: NOSIGNATURE
		mavm-mc1.18.2-forge-1.0.8b.jar                    |More Axolotl Variants Mod     |mavm                          |1.0.8b              |DONE      |Manifest: NOSIGNATURE
		exoticbirds-1.18.2-1.4.0.jar                      |Exotic Birds                  |exoticbirds                   |1.4.0               |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.18.2-4.1.0.461-universal.jar     |CodeChicken Lib               |codechickenlib                |4.1.0.461           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		YungsBetterMineshafts-1.18.2-Forge-2.1.3.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.18.2-Forge-2.1.3  |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.18.2-0.11.0-Alpha2.jar             |Dynamic Trees                 |dynamictrees                  |1.18.2-0.11.0-Alpha2|DONE      |Manifest: NOSIGNATURE
		voidtotem-forge-1.18.2-1.3.1.jar                  |Void Totem                    |voidtotem                     |1.18.2-1.3.1        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.24.jar                    |GeckoLib                      |geckolib3                     |3.0.24              |DONE      |Manifest: NOSIGNATURE
		Hyle-forge-1.18.2-0.1.0.jar                       |Hyle                          |hyle                          |0.1.0               |DONE      |Manifest: NOSIGNATURE
		Unearthed-forge-1.18.2-2.3.1-slim.jar             |Unearthed                     |unearthed                     |2.3.1               |DONE      |Manifest: NOSIGNATURE
		DarkModeEverywhere-1.18.1-1.0.1.jar               |DarkModeEverywhere            |darkmodeeverywhere            |1.18.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		BetterAdvancements-1.18.2-0.2.0.129.jar           |Better Advancements           |betteradvancements            |0.2.0.129           |DONE      |Manifest: NOSIGNATURE
		radium-0.7.10.jar                                 |Radium                        |radium                        |0.7.10              |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		BedBenefits-Forge-1.18.2-6.0.2.jar                |BedBenefits                   |bedbenefits                   |6.0.2               |DONE      |Manifest: NOSIGNATURE
		Alex's Mobs Music Mod.jar                         |Alex's Mobs Mod Music         |peepomod                      |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		rpgz-0.5.0-forge.jar                              |RpgZ                          |rpgz                          |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		DynamicTreesBOP-1.18.2-3.0.0-ALPHA1.jar           |Dynamic Trees for Biomes o' Pl|dtbop                         |1.18.2-3.0.0-ALPHA1 |DONE      |Manifest: NOSIGNATURE
		Cucumber-1.18.2-5.1.1.jar                         |Cucumber Library              |cucumber                      |5.1.1               |DONE      |Manifest: NOSIGNATURE
		InventorySpam-1.18-1.5.0.jar                      |Inventory Spam                |inventoryspam                 |1.5.0               |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1802.3.6-build.123.jar          |FTB Library                   |ftblibrary                    |1802.3.6-build.123  |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1802.2.6-build.51.jar             |FTB Teams                     |ftbteams                      |1802.2.6-build.51   |DONE      |Manifest: NOSIGNATURE
		Tinkers Reforged 1.18.2-1.0.5.jar                 |Tinkers Reforged              |tinkers_reforged              |1.0.5               |DONE      |Manifest: NOSIGNATURE
		TonsOfEnchants-1.18.2-1.0.jar                     |Tons Of Enchantments          |tonsofenchants                |1.0                 |DONE      |Manifest: NOSIGNATURE
		mores-1.3.0.jar                                   |More Ore Stones               |mores                         |1.3.0               |DONE      |Manifest: NOSIGNATURE
		Enlightened End BB V1.5.jar                       |Enlightened End               |nourished_end                 |1.1.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.0.196.jar                          |Just Enough Items             |jei                           |9.7.0.196           |DONE      |Manifest: NOSIGNATURE
		JEIEnchantmentInfo-1.17.1-2.0.0.jar               |JEI Enchantment Info          |jeienchantmentinfo            |1.17.1-2.0.0        |DONE      |Manifest: NOSIGNATURE
		VisualWorkbench-v3.3.0-1.18.2-Forge.jar           |Visual Workbench              |visualworkbench               |3.3.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		LibraryFerret-Forge-1.18.2-1.0.3.jar              |Library ferret                |libraryferret                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.18.2-10.2.4.464.jar                    |Mekanism                      |mekanism                      |10.2.4              |DONE      |Manifest: NOSIGNATURE
		reap-1.18.2-1.0.0.jar                             |Reap Mod                      |reap                          |1.18.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		InvMove-1.18-0.7.0-Forge.jar                      |InvMove                       |invmove                       |0.7.0               |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              |DONE      |Manifest: NOSIGNATURE
		Fallingleaves-1.18.2-1.3.2.jar                    |Falling Leaves                |fallingleaves                 |1.3.2               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+10.jar                  |Clumps                        |clumps                        |8.0.0+10            |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.4.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.4      |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.18.2-1.9.5-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.5-forge  |DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.2-4.0.7.jar                        |Artifacts                     |artifacts                     |1.18.2-4.0.7        |DONE      |Manifest: NOSIGNATURE
		jumpboat-1.18.2-0.1.0.3.jar                       |Jumpy Boats                   |jumpboat                      |1.18.2-0.1.0.3      |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.2.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		rare-ice-0.4.1.jar                                |Rare Ice                      |rare_ice                      |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		lazydfu-1.0-1.18+.jar                             |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE
		starlight-1.0.2+forge.546ae87.jar                 |Starlight                     |starlight                     |1.0.2+forge.83663de |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.18.2-Forge-1.1.0.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.18.2-Forge-1.1.0  |DONE      |Manifest: NOSIGNATURE
		ToastControl-1.18.2-6.0.2.jar                     |Toast Control                 |toastcontrol                  |6.0.2               |DONE      |Manifest: NOSIGNATURE
		EnderStorage-1.18.2-2.9.0.177-universal.jar       |EnderStorage                  |enderstorage                  |2.9.0.177           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		rubidium_extras-1.18.2_v1.3.1.jar                 |Rubidium Extras               |rubidium_extras               |1.18.2_v1.3.1       |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-1802.3.6-build.147.jar           |FTB Chunks                    |ftbchunks                     |1802.3.6-build.147  |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.51-universal.jar                |Forge                         |forge                         |40.1.51             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		MoreCraftingTables+1.18.2-3.2.1.jar               |More Crafting Tables Mod      |mctb                          |1.18.2              |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.7.jar                          |Selene                        |selene                        |1.18.2-1.17.7       |DONE      |Manifest: NOSIGNATURE
		IntegratedCrafting-1.18.2-1.0.23.jar              |IntegratedCrafting            |integratedcrafting            |1.0.23              |DONE      |Manifest: NOSIGNATURE
		craftingtweaks-forge-1.18.2-14.0.3.jar            |CraftingTweaks                |craftingtweaks                |14.0.3              |DONE      |Manifest: NOSIGNATURE
		illagersweararmor-1.1.5.jar                       |Illagers Wear Armor           |zillagersweararmor            |1.1.5               |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TConstruct-1.18.2-3.5.1.31.jar                    |Tinkers' Construct            |tconstruct                    |3.5.1.31            |DONE      |Manifest: NOSIGNATURE
		JER-Integration-3.3.1.jar                         |JER Integration               |jerintegration                |3.3.1               |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.2-10.0.4.jar   |EnchantmentDescriptions       |enchdesc                      |10.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.18.2-1.1.0.102.jar           |TerraBlender                  |terrablender                  |1.18.2-1.1.0.102    |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.18.2-1.18.8.jar                        |Tool Belt                     |toolbelt                      |1.18.8              |DONE      |Manifest: NOSIGNATURE
		titanium-1.18.2-3.5.6-38.jar                      |Titanium                      |titanium                      |3.5.6               |DONE      |Manifest: NOSIGNATURE
		silent-lib-1.18.2-6.2.0.jar                       |Silent Lib                    |silentlib                     |6.2.0               |DONE      |Manifest: NOSIGNATURE
		icepreventscropgrowth_1.18.2-1.5.jar              |Ice Prevents Crop Growth      |icepreventscropgrowth         |1.5                 |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.1.jar                       |Jade                          |jade                          |5.2.1               |DONE      |Manifest: NOSIGNATURE
		inventorytotem_1.18.2-1.6.jar                     |Inventory Totem               |inventorytotem                |1.6                 |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.12_mc1.18.2.jar           |CreativeCore                  |creativecore                  |2.6.12              |DONE      |Manifest: NOSIGNATURE
		ceilingtorch-1.18.2-1.18.jar                      |Ceiling Torch                 |ceilingtorch                  |1.18                |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.2.jar                     |Flywheel                      |flywheel                      |1.18-0.6.2          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.2_v0.4.1.jar                        |Create                        |create                        |0.4.1               |DONE      |Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.27.jar                          |Mantle                        |mantle                        |1.9.27              |DONE      |Manifest: NOSIGNATURE
		brutalbosses-1.18.2-4.9.jar                       |brutalbosses mod              |brutalbosses                  |1.18.2-4.9          |DONE      |Manifest: NOSIGNATURE
		IntegratedDynamics-1.18.2-1.11.2.jar              |IntegratedDynamics            |integrateddynamics            |1.11.2              |DONE      |Manifest: NOSIGNATURE
		integratednbt-1.18.2-1.5.1.jar                    |Integrated NBT                |integratednbt                 |1.5.0               |DONE      |Manifest: NOSIGNATURE
		PigPen-Forge-1.18.2-8.0.1.jar                     |PigPen                        |pigpen                        |8.0.1               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		ecologics-FORGE-1.18.2-1.6.9.jar                  |Ecologics                     |ecologics                     |1.6.9               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |DONE      |Manifest: NOSIGNATURE
		InventoryHud_[1.18].forge-3.4.4.jar               |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.4               |DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.18.2-6.0.3.jar                      |FastFurnace                   |fastfurnace                   |6.0.3               |DONE      |Manifest: NOSIGNATURE
		structures_compass-1.18.2-1.4.1.jar               |Structures Compass            |structures_compass            |1.18.2-1.4.1        |DONE      |Manifest: NOSIGNATURE
		lootr-1.18.2-0.2.17.54.jar                        |Lootr                         |lootr                         |0.2.17.54           |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.2.1-forge.jar                       |Ferrite Core                  |ferritecore                   |0.0NONE             |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		moredragoneggs-3.1.jar                            |More Dragon Eggs              |moredragoneggs                |3.1                 |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.3.5-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.5               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BetterF3-1.2.5-Forge-1.18.2.jar                   |BetterF3                      |betterf3                      |1.2.5               |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.18.2-2.3.6.jar                      |Aquaculture 2                 |aquaculture                   |1.18.2-2.3.6        |DONE      |Manifest: NOSIGNATURE
		bettergolem-1.18.2-1.1.0.jar                      |Better Golem                  |bettergolem                   |1.18.2-1.1.0        |DONE      |Manifest: NOSIGNATURE
		flowerseeds-1.18-2.0.0.jar                        |Flower Seeds                  |flowerseeds                   |1.17.1-2.0.0        |DONE      |Manifest: NOSIGNATURE
		Craftable Horse Armour  Saddle-1.18-1.8-Forge.jar |CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.8                 |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.8.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.2               |DONE      |Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.2-v2.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		valhelsia_core-1.18.2-0.3.1.jar                   |Valhelsia Core                |valhelsia_core                |1.18.2-0.3.1        |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-forge-1.18.2-0.1.0.jar       |Valhelsia Structures          |valhelsia_structures          |1.18.2-0.1.0        |DONE      |Manifest: NOSIGNATURE

**Comment by Jozufozu** [comment]
Fixed in latest flywheel
