### ISSUE TITLE
Rendering crash Supplementaries 

### ISSUE THREAD

**Issue by xAlicatt** [Engine-Room/Flywheel#137]
### Describe the Bug

Placed a modded sign, and I crashed. Unable to get back into the world, due to this crash. 

### Reproduction Steps

1. Placed a sign
2. Crash
3. After reload, either looking at or loading said sign crashes again with the same log
...

### Expected Result

I expected to place a sign and then use it to label a chest for storage purposes

### Crash Report or Log

https://paste.ee/p/pVJsI

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2060 

### Mod Version

0.6.2

### Minecraft Version

1.18

### Loader Version

Forge 40.1.52

### Other Mods

It's in the crash report

**Comment by Jozufozu** [comment]
Looks like an issue with Oh The Biomes You'll Go
