### ISSUE TITLE
Java 15 use with Flywheel 0.2.0: Memory leak

### ISSUE THREAD

**Issue by NighthowlerStudios** [Engine-Room/Flywheel#14]
When using Java 15 with Flywheel 0.2.0 (successfully launched with GDLauncher, my vanilla launcher is currently broken for anything other than 8/16) it causes an INSANE memory leak the faster your game renders chunks.  Turn the character around and you can max out 6GB in MILLISECONDS, causing the game to hang whilst it masscollects.

there are also moments where the render buffer will flash black but they're not as common as this.

**Comment by Jozufozu** [comment]
This doesn't sound like an issue that would be caused by flywheel.
What other mods do you have installed?
Is this behavior different with no mods?
Is this behavior different with a different JRE?

**Comment by NighthowlerStudios** [comment]
JRE 8 runs fine with the same mod list.  All mods in the mod list run fine on JRE 15 without create and flywheel last I checked.

**Comment by NighthowlerStudios** [comment]
Kaleidio's Battle Pack 3.4.5, using a dev branch that updated some mods excluding abnormals core and enhanced mushrooms

**Comment by NighthowlerStudios** [comment]
Finally got around to testing my pack further.  Seems flywheel indeed is not at fault.  I will be investigating this issue amongst the rest of my mods on my own.  Thank you for stabilizing Java 15 though.
