### ISSUE TITLE
After updating to 1.18-0.6.3.jar, previously working game instance crashes on startup

### ISSUE THREAD

**Issue by lOmicronl** [Engine-Room/Flywheel#141]
### Describe the Bug

I made myself a modded Minecraft instance and have been playing in it for over a week now. Flywheel and Create are in it, and there have been no issues with them at any point up until now.

This morning, when launching the game via the Curseforge app, I noticed that there were updates available for Create and Flywheel, and so I installed them. Afterwards, Minecraft started crashing on startup. It crashes so early that no crash report is generated, but latest.log contains a severe error referencing Flywheel right at the end.

Afterwards, I manually downloaded the April releases of Flywheel and Create that I was using before this update, and put them back into my mods folder, deleting the newer versions. Now, Minecraft starts up again just fine.

### Reproduction Steps

Since this may be a cross-mod incompatibility issue with something else in my modlist, I can't offer detailed reproduction steps. For me, it went simply "1.) install latest version, 2.) attempt to start game, 3.) watch it explode".

### Expected Result

I expected the game to launch.

### Crash Report or Log

https://pastebin.com/vkdfYmUe

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1060 6GB

### Mod Version

0.6.3

### Minecraft Version

1.18.2

### Loader Version

Forge 40.1.52

### Other Mods

They are listed in the attached logfile.

**Comment by Jozufozu** [comment]
Not an issue with flywheel. Looks like Create: Steam Powered hasn't updated to Create 0.5 yet
