### ISSUE TITLE
Flywheel crashes with Optifine (1.18.2)

### ISSUE THREAD

**Issue by TwoHeadedGiant** [Engine-Room/Flywheel#143]
### Describe the Bug

I was making a mod pack to test create, some of its addons, little logistics and immersive engineering. I had both optifine and flywheel for 1.18.2 in the pack, I tried launching it and got an error, I saw several mentions of flywheel in the crash log so I came here and saw some others had the same issue. I removed optifine and now it is working. (mod version 0.6.4 im saying it here cause the highest the selector down below goes is 1.6.4)

### Reproduction Steps

1. install optifine
2. install flywheel
3. launch minecraft

### Expected Result

minecraft crashes

### Screenshots and Videos

![Screenshot 2022-07-11 200214](https://user-images.githubusercontent.com/109116550/178378476-22f4d058-4a47-4bc6-aa2b-8d2430ae19ae.jpg)

### Crash Report or Log

---- Minecraft Crash Report ---- // Hi. I'm Minecraft, and I'm a crashaholic.  Time: 7/11/22, 7:33 PM Description: Exception in server tick loop  java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)' 	at net.minecraft.server.level.ServerChunkCache.addRegionTicket(ServerChunkCache.java:429) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ServerChunkCache.m_8387_(ServerChunkCache.java:425) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:471) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A} 	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A} 	at java.lang.Thread.run(Thread.java:833) [?:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- System Details -- Details: 	Minecraft Version: 1.18.2 	Minecraft Version ID: 1.18.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.1, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 3356784352 bytes (3201 MiB) / 5716836352 bytes (5452 MiB) up to 8388608000 bytes (8000 MiB) 	CPUs: 12 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz 	Identifier: Intel64 Family 6 Model 165 Stepping 2 	Microarchitecture: unknown 	Frequency (GHz): 2.59 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x2520 	Graphics card #0 versionInfo: DriverVersion=27.21.14.6179 	Graphics card #1 name: Intel(R) UHD Graphics 	Graphics card #1 vendor: Intel Corporation (0x8086) 	Graphics card #1 VRAM (MB): 1024.00 	Graphics card #1 deviceId: 0x9bc4 	Graphics card #1 versionInfo: DriverVersion=27.20.100.8280 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 26470.16 	Virtual memory used (MB): 23167.71 	Swap memory total (MB): 10255.11 	Swap memory used (MB): 1337.69 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m 	Server Running: true 	Player Count: 0 / 8; [] 	Data Packs: vanilla, mod:create_stuff_additions, mod:jei (incompatible), mod:caelus (incompatible), mod:modnametooltip (incompatible), mod:neat (incompatible), mod:waystones (incompatible), mod:easyelytratakeoff, mod:createab (incompatible), mod:clumps (incompatible), mod:journeymap, mod:controlling (incompatible), mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:naturescompass (incompatible), mod:artifacts, mod:storagenetwork (incompatible), mod:decorative_blocks, mod:dungeoncrawl, mod:curioofundying (incompatible), mod:bookshelf, mod:create_confectionery, mod:littlecontraptions (incompatible), mod:bonsaitrees3, mod:uteamcore, mod:createcurios, mod:balm (incompatible), mod:carryon (incompatible), mod:jeresources (incompatible), mod:forge, mod:dummmmmmy (incompatible), mod:createcafe (incompatible), mod:corpse (incompatible), mod:usefulbackpacks, mod:enchdesc (incompatible), mod:terrablender (incompatible), mod:mousetweaks (incompatible), mod:immersiveengineering, mod:biomesoplenty (incompatible), mod:flywheel (incompatible), mod:create, mod:createdeco (incompatible), mod:createplus (incompatible), mod:curios (incompatible), mod:durableelytra, mod:create_factory, mod:collective, mod:dragondropselytra, mod:libnonymous, mod:littlelogistics (incompatible), mod:architectury (incompatible), mod:curiouselytra (incompatible), mod:fastleafdecay, mod:expandability (incompatible), mod:cosmeticarmorreworked (incompatible), mod:xpbook (incompatible) 	World Generation: Stable 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge' 	OptiFine Version: OptiFine_1.18.2_HD_U_H7 	OptiFine Build: 20220410-185216 	Render Distance Chunks: 8 	Mipmaps: 4 	Anisotropic Filtering: 1 	Antialiasing: 0 	Multitexture: false 	Shaders: null 	OpenGlVersion: 3.2.0 NVIDIA 461.79 	OpenGlRenderer: GeForce RTX 3060 Laptop GPU/PCIe/SSE2 	OpenGlVendor: NVIDIA Corporation 	CpuCount: 12 	ModLauncher: 9.1.3+9.1.3+main.9b69c82a 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		 mixin PLUGINSERVICE  		 eventbus PLUGINSERVICE  		 slf4jfixer PLUGINSERVICE  		 object_holder_definalize PLUGINSERVICE  		 runtime_enum_extender PLUGINSERVICE  		 capability_token_subclass PLUGINSERVICE  		 accesstransformer PLUGINSERVICE  		 runtimedistcleaner PLUGINSERVICE  		 mixin TRANSFORMATIONSERVICE  		 OptiFine TRANSFORMATIONSERVICE  		 fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		create-stuff-additions1.18.2_v1.1.7.jar           |Create Stuff Additions        |create_stuff_additions        |1.1.7               |DONE      |Manifest: NOSIGNATURE 		jei-1.18.2-9.7.0.209.jar                          |Just Enough Items             |jei                           |9.7.0.209           |DONE      |Manifest: NOSIGNATURE 		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |DONE      |Manifest: NOSIGNATURE 		modnametooltip-1.18.1-1.18.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.18.0              |DONE      |Manifest: NOSIGNATURE 		Neat-1.8-31.jar                                   |Neat                          |neat                          |1.8-31              |DONE      |Manifest: NOSIGNATURE 		waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              |DONE      |Manifest: NOSIGNATURE 		easyelytratakeoff_1.18.2-2.2.jar                  |Easy Elytra Takeoff           |easyelytratakeoff             |2.2                 |DONE      |Manifest: NOSIGNATURE 		createab-1.18.2_v0.1.jar                          |CreateArmoredCopperBacktanks  |createab                      |1.18.2_v0.1         |DONE      |Manifest: NOSIGNATURE 		Clumps-forge-1.18.2-8.0.0+10.jar                  |Clumps                        |clumps                        |8.0.0+10            |DONE      |Manifest: NOSIGNATURE 		journeymap-1.18.2-5.8.5-forge.jar                 |Journeymap                    |journeymap                    |5.8.5               |DONE      |Manifest: NOSIGNATURE 		Controlling-forge-1.18.2-9.0+21.jar               |Controlling                   |controlling                   |9.0+21              |DONE      |Manifest: NOSIGNATURE 		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE 		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |DONE      |Manifest: NOSIGNATURE 		NaturesCompass-1.18.2-1.9.7-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.7-forge  |DONE      |Manifest: NOSIGNATURE 		artifacts-1.18.2-4.0.7.jar                        |Artifacts                     |artifacts                     |1.18.2-4.0.7        |DONE      |Manifest: NOSIGNATURE 		SimpleStorageNetwork-1.18.2-1.6.2.jar             |Simple Storage Network        |storagenetwork                |1.18.2-1.6.2        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed 		Decorative Blocks-forge-1.18.2-2.1.0.jar          |Decorative Blocks             |decorative_blocks             |2.1.0               |DONE      |Manifest: NOSIGNATURE 		DungeonCrawl-1.18.2-2.3.10.jar                    |Dungeon Crawl                 |dungeoncrawl                  |2.3.10              |DONE      |Manifest: NOSIGNATURE 		curioofundying-forge-1.18-5.3.0.0.jar             |Curio of Undying              |curioofundying                |1.18-5.3.0.0        |DONE      |Manifest: NOSIGNATURE 		Bookshelf-Forge-1.18.2-13.2.21.jar                |Bookshelf                     |bookshelf                     |13.2.21             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5 		create-confectionery1.18.2_v1.0.8.jar             |Create Confectionery          |create_confectionery          |1.0.8               |DONE      |Manifest: NOSIGNATURE 		littlecontraptions-forge-1.18.2.0.jar             |Little Contraptions           |littlecontraptions            |1.18.2.0            |DONE      |Manifest: NOSIGNATURE 		bonsaitrees3-3.1.0.jar                            |Bonsai Trees 3                |bonsaitrees3                  |3.1.0               |DONE      |Manifest: NOSIGNATURE 		u_team_core-1.18.2-4.0.1.216.jar                  |U Team Core                   |uteamcore                     |4.0.1.216           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0 		Create-Curios-1.18.2-v1.0.0.jar                   |Create Curios                 |createcurios                  |1.0.0               |DONE      |Manifest: NOSIGNATURE 		balm-3.1.0+0.jar                                  |Balm                          |balm                          |3.1.0+0             |DONE      |Manifest: NOSIGNATURE 		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |DONE      |Manifest: NOSIGNATURE 		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE 		forge-1.18.2-40.1.60-universal.jar                |Forge                         |forge                         |40.1.60             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		MmmMmmMmmMmm-1.18.2-1.5.2.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.18-1.5.2          |DONE      |Manifest: NOSIGNATURE 		createcafe-1.4-1.18.2.jar                         |Create Cafe                   |createcafe                    |1.4-1.18.2          |DONE      |Manifest: NOSIGNATURE 		corpse-1.18.2-1.0.1.jar                           |Corpse                        |corpse                        |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE 		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		useful_backpacks-1.18.2-1.12.2.94.jar             |Useful Backpacks              |usefulbackpacks               |1.12.2.94           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0 		EnchantmentDescriptions-Forge-1.18.2-10.0.4.jar   |EnchantmentDescriptions       |enchdesc                      |10.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5 		TerraBlender-forge-1.18.2-1.1.0.102.jar           |TerraBlender                  |terrablender                  |1.18.2-1.1.0.102    |DONE      |Manifest: NOSIGNATURE 		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE 		ImmersiveEngineering-1.18.2-8.0.2-149.jar         |Immersive Engineering         |immersiveengineering          |1.18.2-8.0.2-149    |DONE      |Manifest: NOSIGNATURE 		BiomesOPlenty-1.18.2-16.0.0.109-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.109   |DONE      |Manifest: NOSIGNATURE 		flywheel-forge-1.18-0.6.4.jar                     |Flywheel                      |flywheel                      |1.18-0.6.4.87       |DONE      |Manifest: NOSIGNATURE 		create-mc1.18.2_v0.5.0a.jar                       |Create                        |create                        |0.5.0a              |DONE      |Manifest: NOSIGNATURE 		createdeco-1.2.8-1.18.2.jar                       |Create Deco                   |createdeco                    |1.2.8-1.18.2        |DONE      |Manifest: NOSIGNATURE 		createplus-1.18.2_v0.5.0.jar                      |Create Plus                   |createplus                    |1.18.2_v0.5.0       |DONE      |Manifest: NOSIGNATURE 		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |DONE      |Manifest: NOSIGNATURE 		durableelytra.jar                                 |Durable Elytra                |durableelytra                 |1.0.0               |DONE      |Manifest: NOSIGNATURE 		create-factory-1.18.2-v1.6.jar                    |Create: Factory               |create_factory                |1.6                 |DONE      |Manifest: NOSIGNATURE 		collective-1.18.2-4.28.jar                        |Collective                    |collective                    |4.28                |DONE      |Manifest: NOSIGNATURE 		dragondropselytra_1.18.2-1.5.jar                  |Dragon Drops Elytra           |dragondropselytra             |1.5                 |DONE      |Manifest: NOSIGNATURE 		libnonymous-2.1.0.jar                             |libnonymous                   |libnonymous                   |2.1.0               |DONE      |Manifest: NOSIGNATURE 		littlelogistics-mc1.18.2-v1.2.5.jar               |Little Logistics              |littlelogistics               |1.2.5               |DONE      |Manifest: NOSIGNATURE 		architectury-4.5.76-forge.jar                     |Architectury                  |architectury                  |4.5.76              |DONE      |Manifest: NOSIGNATURE 		curiouselytra-forge-1.18.1-5.0.1.0.jar            |Curious Elytra                |curiouselytra                 |1.18.1-5.0.1.0      |DONE      |Manifest: NOSIGNATURE 		FastLeafDecay-28.jar                              |FastLeafDecay                 |fastleafdecay                 |28                  |DONE      |Manifest: NOSIGNATURE 		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |DONE      |Manifest: NOSIGNATURE 		CosmeticArmorReworked-1.18.2-v2.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53 		xptome-1.18.2-2.1.6.jar                           |XP Tome                       |xpbook                        |2.1.6               |DONE      |Manifest: NOSIGNATURE 	Flywheel Backend: GL33 Instanced Arrays 	Crash Report UUID: 17b597e5-8b0d-4e42-9175-03880db86eb1 	FML: 40.1 	Forge: net.minecraftforge:40.1.60

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3060 Laptop GPU

### Mod Version

0.6.2

### Minecraft Version

1.18.1

### Loader Version

Forge 40.1.60

### Other Mods

optifine

**Comment by Jozufozu** [comment]
This is a bug with Optifine. I get the same crash on Forge 40.1.60 with Optifine HD U7, and no Flywheel.
