### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by red-grump-panda** [Engine-Room/Flywheel#144]
### Describe the Bug

Crash at startup:

First there's minecraft as a minimised window, just filled with white
Then there's the red Mojang loading screen, as usual
However then it switches to the minecraft dirt texture with nothing but "[][][][][][] [][][][][]" written on it
Then it crashes

### Reproduction Steps

1. Open Launcher 
2. Start game 
3. Crash
...

### Expected Result

No crash, and no dirt texture with "[][][][][][] [][][][][]" 

### Screenshots and Videos

![](https://cdn.discordapp.com/attachments/798831384511774731/999004753533091960/IMG_9931.jpg)
![](https://cdn.discordapp.com/attachments/798831384511774731/999004753281425418/IMG_9932.jpg)
![](https://cdn.discordapp.com/attachments/798831384511774731/999004153831506001/IMG_9936.png)

### Crash Report or Log

https://pastebin.com/8YURWHYU

### Operating System

Windows 11

### What is your GPU?

AMD Radeon HD 7800 Series

### Mod Version

0.6.4

### Minecraft Version

1.18.1

### Loader Version

Forge 40.1.68

### Other Mods

create mod

### Additional Context

 **The "minecraft version" didn't let me select 1.18.2 It should be 1.18.2**

**Comment by Jozufozu** [comment]
Delete `flywheel-client.toml` from your config folder

**Comment by DeltaRobot314** [comment]
I am having the same issue and deleting flywheel-client.toml does nothing
