### ISSUE TITLE
Loading game crashes

### ISSUE THREAD

**Issue by ghost** [Engine-Room/Flywheel#147]
### Describe the Bug

Loading game crashes minecraft1.18.2

### Reproduction Steps

1.minecraft 1.18.2
2.Loading game crashes
3.
...

### Expected Result

[minecraft-exported-logs-2022-08-15T10-57-47.log](https://github.com/Jozufozu/Flywheel/files/9334848/minecraft-exported-logs-2022-08-15T10-57-47.log)

### Operating System

10

### What is your GPU?

rtx3060

### Mod Version

0.6.5

### Minecraft Version

1.18.1

### Loader Version

forge40.1.73

### Other Mods

did not see 1.18.2 So choose 1.18.1

**Comment by Jusey1** [comment]
The mod is supposed to work for 1.18.2 just fine and has been then 0.6.5 came out and it crashes upon launch, so going to stick to 0.6.4 until this is resolved.

**Comment by ghost** [comment]
> 该 mod 应该适用于 1.18.2 就好了，然后 0.6.5 出来了，它在启动时崩溃了，所以要坚持使用 0.6.4 直到这个问题得到解决。

ok

**Comment by Jozufozu** [comment]
Same as #148
