### ISSUE TITLE
Block light flickering, probable shader issue

### ISSUE THREAD

**Issue by NighthowlerStudios** [Engine-Room/Flywheel#15]
With flywheel, create, and Starlight Create 1.16.5 rc2 installed, blocks on the ground flicker black then back to their assigned lighting.  it is entirely random.

**Comment by Jozufozu** [comment]
Does this happen without flywheel/create installed?

**Comment by NighthowlerStudios** [comment]
no, it only happens when Flywheel 0.2 and starlight create compat rc2 are installed together.

**Comment by Jozufozu** [comment]
Could you post a link to the starlight create compat?

**Comment by NighthowlerStudios** [comment]
https://github.com/AeiouEnigma/Starlight/releases/tag/1.0.0-RC2-Create-2

**Comment by Cynix32** [comment]
I experience the same problem. I have my own personal modpack and this flickering issue also happens with the commonality of this issue being that I also use Flywheel 0.2 & Starlight RC2. SO i guess it maybe has something to do with flywheel and starlight having some sort of conflict.

**Comment by Cynix32** [comment]
So far, I have played again using flywheel 0.1.1 + Starlight RC2. No flickering. The flickering only happens on flywheel 0.2 + Starlight RC2

**Comment by NighthowlerStudios** [comment]
Exact same behaviour for me.

**Comment by NighthowlerStudios** [comment]
Seemingly this block light misbehaviour has disappeared since 0.2.1, thanks dev.
