### ISSUE TITLE
[1.18.2] Running latest flywheel yet it shows there is an update available

### ISSUE THREAD

**Issue by WFPhantom** [Engine-Room/Flywheel#150]
### Describe the Bug

Running flywheel 0.6.5 as seen in the screenshot below, which is the latest version available on curseforge but it shows that there is an update available.

### Reproduction Steps

1. Run game
2. Green icon for updates is there

### Expected Result

1. Run game
2. Green icon for updates isn't there

### Screenshots and Videos

https://imgur.com/a/me6ZK0Z

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 970

### Mod Version

0.6.5

### Minecraft Version

1.18.2

### Loader Version

Forge - 40.1.73

### Other Mods

[Catalogue](https://www.curseforge.com/minecraft/mc-mods/catalogue) for showing the modlist in game

**Comment by Jozufozu** [comment]
Thank you! Should be fixed if you relaunch your game

**Comment by WFPhantom** [comment]
Yep it's fixed thank you!
