### ISSUE TITLE
Says I need a higher version to use Create, but needs lower version for Create: Big Cannons add on

### ISSUE THREAD

**Issue by IIEnderGabeII** [Engine-Room/Flywheel#151]
### Describe the Bug

So, when loading into the forge version, it always says you need either flywheel 0.6.5 or higher, or 0.6.3. Now, I tried using both at the same time and I guess that cancels one out.

### Reproduction Steps

1. Install all the required applications for Create + Create: Big Cannons (Forge, Flywheel, etc)
2. Load into Minecraft
...

### Expected Result

I expected it to load the mod along with the added add-on. 

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/111608602/185697056-789965b1-fac9-46c9-b674-e088efaf8409.png)
![image](https://user-images.githubusercontent.com/111608602/185697114-0f7d2f2e-9f53-447a-be6f-3edf94d0355d.png)

### Crash Report or Log

I cannot find where to get it.

### Operating System

Windows 11

### What is your GPU?

I do not know

### Mod Version

0.6.3

### Minecraft Version

1.18.2

### Loader Version

Forge 40.1.60

### Other Mods

None

**Comment by Jozufozu** [comment]
Please wait for big cannons to update to the latest create version, or downgrade create/flywheel
