### ISSUE TITLE
Flywheel crash whit Optifine (1.19)

### ISSUE THREAD

**Issue by Guppy3874** [Engine-Room/Flywheel#153]
### Describe the Bug

Hello first I wanted to say, yes I know this is not a finished version of the mod. But I wanted to report a bug. The 1.19.2 version of the mod not compatible with Optifine and crashes as soon as the loading of the Game has begun. so that's it good luck furthermore :)

### Reproduction Steps

1.Launch the Game in 1.19.2 + Optifine
2.wait until it crash
...

### Expected Result

The Game does not Crash

### Crash Report or Log

https://pastebin.com/QTLpRdqP

### Operating System

Windows 11

### What is your GPU?

RTX 2070 Super

### Mod Version

0.6.5

### Minecraft Version

1.19.2

### Loader Version

Forge 43.1.25

### Other Mods

Optfine HD U H9  --  (HD U I1 also crash)
Create 1.19

**Comment by PepperCode1** [comment]
This is not a Flywheel issue. Your version of Optifine does not work with your version of Forge, so you can downgrade Forge, update Optifine if there is an update, or uninstall Optifine.

**Comment by Guppy3874** [comment]
ok, now i use the correct version of Forge and the Game starts now. But if you now loade a world it crash as soon as the Loading is complete.
