### ISSUE TITLE
Flywheel has failed to load correctly

### ISSUE THREAD

**Issue by mcjojo3** [Engine-Room/Flywheel#159]
### Describe the Bug

Flywheel cannot load during startup

### Reproduction Steps

1. Use my modpack
2. Profit

### Expected Result

It booting

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/38841486/204664416-94588119-d5f9-4693-b593-b9a79881b7d1.png)

[crash-2022-11-29_23.39.25-fml.txt](https://github.com/Jozufozu/Flywheel/files/10117901/crash-2022-11-29_23.39.25-fml.txt)
[crash-2022-11-29_23.37.54-client.txt](https://github.com/Jozufozu/Flywheel/files/10117902/crash-2022-11-29_23.37.54-client.txt)

### Crash Report or Log

For some reason pastbin deemed my file dangerous or something so I uploaded them above

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3070 Laptop GPU

### Mod Version

0.6.5

### Minecraft Version

1.18.2

### Loader Version

Forge - 40.1.84

### Other Mods

[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Ultimate Car Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod)
[Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[No Null Processors (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/no-null-processors)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Dynamic View[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)
[Immersive Engineering (by BluSunrize)](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
[Thermal Integration (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-integration)
[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[Mine Gear Rising: Revengeance (by mc_jojo3)](https://www.curseforge.com/minecraft/mc-mods/mgrr)
[FTB Ranks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-forge)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[Seamless Loading Screen (Forge) (by TimScript)](https://www.curseforge.com/minecraft/mc-mods/seamless-loading-screen-forge)
[WTHIT Forge Edition (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit-forge)
[CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
[Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
[FindMe (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/findme)
[Create Plus (by Robocraft999)](https://www.curseforge.com/minecraft/mc-mods/create-plus)
[Thermal Foundation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[CC: Tweaked (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
[More MobGriefing Options (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/more-mobgriefing-options)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
[KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Thermal Cultivation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Collective (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[League of Troglodytes (by mc_jojo3)](https://www.curseforge.com/minecraft/mc-mods/lot)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Gauges and Switches (by wilechaote)](https://www.curseforge.com/minecraft/mc-mods/redstone-gauges-and-switches)
[Mantle (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/mantle)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Industrial Foregoing (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing)
[Ding (by ohaiiChun)](https://www.curseforge.com/minecraft/mc-mods/ding)
[Electrodynamics (by aurilisdev)](https://www.curseforge.com/minecraft/mc-mods/electrodynamics)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Minezedge Music (by mc_jojo3)](https://www.curseforge.com/minecraft/mc-mods/minezedge-music)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Eyes in the Darkness (by gigaherz)](https://www.curseforge.com/minecraft/mc-mods/eyes-in-the-darkness)
[Pollution of the Realms (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms)
[The Accurate Backrooms (by shady8720)](https://www.curseforge.com/minecraft/mc-mods/the-accurate-backrooms)
[Inventory Spam (by gigaherz)](https://www.curseforge.com/minecraft/mc-mods/inventory-spam)
[Memory Settings[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/memory-settings)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[JourneyMap Server (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap-server)
[Easy Magic (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Magnum Torch (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge)
[KubeJS Mekanism (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs-mekanism)
[Blastcraft mod (by aurilisdev)](https://www.curseforge.com/minecraft/mc-mods/blast-craft)
[Chisels & Bits - For Forge (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
[FEATCU (by mc_jojo3)](https://www.curseforge.com/minecraft/mc-mods/featcu)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Delete Item (by DoubleDoorDev)](https://www.curseforge.com/minecraft/mc-mods/delete-item)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Create Chunkloading (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/create-chunkloading)
[CreRaces (by mc_jojo3)](https://www.curseforge.com/minecraft/mc-mods/creraces)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Simply Light (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-light)
[Visual Workbench (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Leave My Bars Alone (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/leave-my-bars-alone)
[Server Tab Info (by black_dog20)](https://www.curseforge.com/minecraft/mc-mods/server-tab-info)
[DEUF - Duplicate Entity UUID Fix (by CAS_ual_TY)](https://www.curseforge.com/minecraft/mc-mods/deuf-duplicate-entity-uuid-fix)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Thermal Locomotion (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-locomotion)
[True Darkness (by GrondagTheBarbarian)](https://www.curseforge.com/minecraft/mc-mods/true-darkness)
[Corail Pillar (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-pillar)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Thermal Innovation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-innovation)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Tinkers Construct (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)
[KubeJS Create (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs-create)
[Mowzie's Mobs (by bobmowzie)](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs)
[Twilight Tweaks (by jodlodi)](https://www.curseforge.com/minecraft/mc-mods/twilight-tweaks)
[JourneyMap Integration (by frankv_)](https://www.curseforge.com/minecraft/mc-mods/journeymap-integration)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Diagonal Fences (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)
[Radon (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radon)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Villager Names (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Advanced Peripherals (by srrendi)](https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals)
[Fastload (by FluffyBumblebe3)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Farming for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads)
[Minezedge Economy (by mc_jojo3)](https://www.curseforge.com/minecraft/mc-mods/minezedge-economy)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Magnesium/Rubidium Extras (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[Create : Misc & Things (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[CC:C Bridge (by Sammy_echt)](https://www.curseforge.com/minecraft/mc-mods/cccbridge)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Get In The Bucket Mod (by hardcorshik31)](https://www.curseforge.com/minecraft/mc-mods/get-in-the-bucket-mod)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Botania (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania)
[Modern Life (by Darimus)](https://www.curseforge.com/minecraft/mc-mods/modern-life)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[It Takes a Pillage (by izofar)](https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[Better Compatibility Checker (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Limited Chunkloading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/limited-chunkloading)
[Evershock (by mc_jojo3)](https://www.curseforge.com/minecraft/mc-mods/evershock)
[Create: Factory (by antopfr90)](https://www.curseforge.com/minecraft/mc-mods/create-factory)
[Villager Death Messages (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-death-messages)
[Chunk-Pregenerator (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Double Doors (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[Create: Broken Bad (by jetpacker06)](https://www.curseforge.com/minecraft/mc-mods/create-broken-bad)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Advanced Chimneys (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys)
[Tiny Skeletons (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/tiny-skeletons-forge)
[It Shall Not Tick (ISNT) (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/it-shall-not-tick)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Tinkers' Integrations and Tweaks (by wendall911)](https://www.curseforge.com/minecraft/mc-mods/tcintegrations)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Krypton Reforged (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/krypton-reforged)
[Simple Discord Rich Presence (Forge / Fabric) (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence)
[Coffee Spawner (by Ruuubi)](https://www.curseforge.com/minecraft/mc-mods/coffee-spawner)
[KubeJS Thermal (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs-thermal)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[PolyLib (by Official_CreeperHost)](https://www.curseforge.com/minecraft/mc-mods/polylib)
[ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
[MCA Reborn [Fabric/Forge] (by jahx_senpoopie)](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn)
[JEITweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/jeitweaker)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[Memory Usage Screen [Forge/Fabric] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/memory-usage-screen)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Ballistix (by aurilisdev)](https://www.curseforge.com/minecraft/mc-mods/ballistix)
[Tinkers Reforged (by mrthomas20121)](https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Nuclear Science (by aurilisdev)](https://www.curseforge.com/minecraft/mc-mods/nuclear-science)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Essentials (by Technomancer_isTaken)](https://www.curseforge.com/minecraft/mc-mods/essentials)
[Applied Energistics 2 (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[WYML (by Official_CreeperHost)](https://www.curseforge.com/minecraft/mc-mods/wyml)
[DrawerFPS (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/drawerfps)
[Ensorcellation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/ensorcellation)
[PackMenu (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/packmenu)
[Thermal Expansion (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)
[ConnectedTexturesMod (by tterrag1098)](https://www.curseforge.com/minecraft/mc-mods/ctm)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
[ViesCraft Machines (by Vies)](https://www.curseforge.com/minecraft/mc-mods/viescraft-airships)
[Out Of Sight (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/out-of-sight)
[Create Cafe (by 1mphuls3)](https://www.curseforge.com/minecraft/mc-mods/create-cafe)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Create: Extended Flywheels (by rabbitminers)](https://www.curseforge.com/minecraft/mc-mods/create-extended-flywheels)
[CreateTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/createtweaker)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Create: Alloyed (by MythrilBagels)](https://www.curseforge.com/minecraft/mc-mods/create-alloyed)
[Applied Botanics Addon (by ramidzkh)](https://www.curseforge.com/minecraft/mc-mods/applied-botanics-addon)
[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Titanium (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/titanium)
[Simple Planes (Forge) (by przemykomo)](https://www.curseforge.com/minecraft/mc-mods/simple-planes)
[Puzzles Lib (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Nostalgic Tweaks (Fabric/Forge) (by Adrenix_Live)](https://www.curseforge.com/minecraft/mc-mods/nostalgic-tweaks)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Applied Mekanistics (by ramidzkh)](https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics)
[More Minecarts and Rails (by goldey3)](https://www.curseforge.com/minecraft/mc-mods/more-minecarts)

### Additional Context

Updated recently some mods

**Comment by PepperCode1** [comment]
This is caused by `MemoryUsageScreen-1.18-Forge-1.5.jar`, not Flywheel.
