### ISSUE TITLE
Incompatibility with Create: Big Cannons

### ISSUE THREAD

**Issue by Sokya88** [Engine-Room/Flywheel#163]
It says Big Cannons need version 6.9 of Flywheel, yet I see only 6.8 as the latest version of flywheel. If this is just me being an idiot, and you know how to fix this, please tell me, but if it's a coding issue, then this issue still stands.

**Comment by PepperCode1** [comment]
It is Big Cannon's responsibility to update to new versions of Flywheel. However, Flywheel 0.6.9 does not exist yet, so if Big Cannons really does require a version of Flywheel that does not exist, they need to fix that.

**Comment by thebushboi** [comment]
there is no 6.9 version of flywheel only 6.8 and you need 6.9 to play create big cannons so currently I cant play create big cannons this needs to be fixed please.

**Comment by PrototypeTrousers** [comment]
https://createmod.net/whywheel/
