### ISSUE TITLE
rendering issue with chest and similar blocks

### ISSUE THREAD

**Issue by skybix** [Engine-Room/Flywheel#164]
flywheel-forge-1.18.2-0.6.8.jar

tried forge versions 40.1.0 , 40.1.86 , and 40.1.85

![2022-12-16_22 17 50](https://user-images.githubusercontent.com/74844027/208228757-b1e1be33-471e-4efa-8875-31c3e49130b8.png)

chests, enderchests, trapped chests, shulker boxs, and bells have issues rendering textures from certain angles.

**Comment by Haloslayer** [comment]
Oh my god I have been troubleshooting for days now trying to figure out WHY. Current work around:  /flywheel backend off (Type it in game)

This has sent me on a wild goose chase around the internet due to the error it throws in the crash logs. I have updated drivers, windows, Done DISM, SFC Scannows, Reverted drivers, etc. 

The last time this issue popped up was for AMD GPU's Which Surprise surprise... I have. Do you?

Nothing pointed to create until I finally narrowed it down to mods and flipped them on 1 by 1.

**Comment by MeloTheRogue** [comment]
@Haloslayer firstly THANK YOU! i have the exact same issue and did all of those same troubleshooting steps. i also have an an AMD GPU (6800XT). running that command allows me to play the game with Flywheel for more than 2 seconds after loading into a world or a server.

if its helpful for resolving the issue, i've got a 1060 i can switch to.

to also add additional info my friends were all able to join the server, they have 1060, 1080, 1080 and 3080TI.

**Comment by Haloslayer** [comment]
To also note this occurs on 1.18.2 as well

**Comment by MeloTheRogue** [comment]
can confirm, thats the version i'm playing on

**Comment by Wolfability** [comment]
I have this same issue in 1.18.2. AMD 5700xt GPU. It definitely seems to be an AMD issue since I'm the only one among my friends with the problem on the server, none of them have AMD.

Edit: Changing to "  /flywheel backend batching  " seems to also fix the issue without disabling it completely.

**Comment by MC-Valdreth** [comment]
Thank you! I was having a hard time tracking down which mod was causing this issue for me. I'm using a AMD Radeon HD 6450. The "/flywheel backend batching" command seems to have fixed the issue for me.

**Comment by PepperCode1** [comment]
This issue was just fixed in commit 83a5723420a24112dbd77a02135e710d6b37de2f. A release of Flywheel and Create for 1.18.2 and 1.19.2 will be made relatively soon.

**Comment by ambientNexus** [comment]
If the latest commit has already fixed the crash and rendering issues, how come it still hasn't been compiled and uploaded to curseforge/modrinth? Seems like a pointless delay, in all honesty.

**Comment by PepperCode1** [comment]
Flywheel 0.6.8.a for 1.18.2 and 1.19.2 with the fix for this issue have just been uploaded to CurseForge and Modrinth.
