### ISSUE TITLE
The animation when a block is broken is broken [CHEST]

### ISSUE THREAD

**Issue by Lolothepro** [Engine-Room/Flywheel#175]
### Describe the Bug

\\

### Reproduction Steps

\\

### Expected Result

That the texture when breaking a block is centred

### Screenshots and Videos

![2023-04-24_22 01 26](https://user-images.githubusercontent.com/68275908/234103827-de4cbbf2-c4ba-4deb-acc7-0a5c4559bda2.png)

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

Fabric 0.14.19

### Other Mods

Fabric API 0.76.0+1.19.2

**Comment by PepperCode1** [comment]
This was fixed in Flywheel 0.6.9.
