### ISSUE TITLE
1.16.5 Chunks random glitches

### ISSUE THREAD

**Issue by ghost** [Engine-Room/Flywheel#18]
Hello, after updating the mod to version Flywheel-1.16-0.2.0, mystical events began to happen on my server, some players began to see blocks from other chunks in one chunk. When I rolled back the version of the mod, the bug disappeared. This happens randomly, at times you can observe that the chunks are not reloaded, or somehow two different chunks are combined for a while, then if you move away from this place, then everything falls into place. In some places, frames drop noticeably, which was also noticed by some players.

![Screenshot_3](https://user-images.githubusercontent.com/36424845/127787980-7fbe24bd-7bd0-4ae0-ab63-6f656b897643.png)

Then when I moved a little from this place, after a few seconds

![Screenshot_4](https://user-images.githubusercontent.com/36424845/127788017-626ad55d-ff11-410b-b5fd-36ea1841f412.png)

**Comment by Jozufozu** [comment]
Should be fixed in [this patch](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3411101).

**Comment by ghost** [comment]
Thank you, you are amazing)

**Comment by Jozufozu** [comment]
Glad it helped!
