### ISSUE TITLE
OOM Error trying to resize buffer from 2145389568 bytes to -2147480576 bytes

### ISSUE THREAD

**Issue by cvrunmin** [Engine-Room/Flywheel#181]
### Describe the Bug

As title described, when you played long enough time, the game crashes by OutOfMemoryError: Failed to resize buffer from 2145389568 bytes to -2147480576 bytes. It seems happen when our server people starts building heavy machine from Create but we are stilling asking other players if such problem happen before that timing.

### Reproduction Steps

1. join a modded server with heavy machine
2. play about a hour
3. the game crashes

### Expected Result

It shall not crash. Especially it should not reallocate negative amount of memory.

### Screenshots and Videos

You may take this as a reference what 'heavy machine' refers to in this context:
![2023-05-17_15 04 24](https://github.com/Jozufozu/Flywheel/assets/8142687/0d74ef28-6eed-4586-99fb-f24369e5a838)

### Crash Report or Log
latest.log:
https://pastebin.com/FHwCsbBD
crash report:
https://pastebin.com/ftLcQyiJ

### Operating System

Windows 10

### What is your GPU?

RTX 2060

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

Forge 43.2.0

### Other Mods

okzoomer-forge-1.19-2.1.1.jar                    
inventorysorter-1.19.2-21.0.4.jar                
libIPN-forge-1.19-2.0.7.jar                      
MouseTweaks-forge-mc1.19-2.23.jar                
pamhc2trees-1.19.2-1.0.1.jar                     
pamhc2crops-1.19.2-1.0.2.jar                     
beenfo-1.19.1-forge42.0.1-1.2.jar                
jei-1.19.2-forge-11.6.0.1015.jar                 
wthit-forge-5.15.4.jar                           
pamhc2foodextended-1.19.2-1.0.0.jar              
kffmod-3.12.0.jar                                
flywheel-forge-1.19.2-0.6.8.a-14.jar             
create-1.19.2-0.5.0.i.jar                        
createdeco-1.3.2-1.19.2.jar                      
Xaeros_Minimap_23.4.1_Forge_1.19.1.jar           
pamhc2foodcore-1.19.2-1.0.0.jar                  
XaerosWorldMap_1.30.1_Forge_1.19.1.jar           
cookingforblockheads-forge-1.19.2-13.3.2.jar     
StorageDrawers-1.19-11.1.2.jar                   
configured-2.1.1-1.19.2.jar                      
badpackets-forge-0.2.1.jar                       
InventoryProfilesNext-forge-1.19-1.9.7.jar       
architectury-6.5.82-forge.jar                    
Steam_Rails-1.2.6+forge-mc1.19.2.jar             
SoL-Carrot-1.19.2-1.14.0.jar                     
EasierVillagerTrading-forge-1.19.2-1.2.0.jar     
catalogue-1.7.0-1.19.2.jar
balm-forge-1.19.2-4.5.7.jar
quickpacketfix-1.0.jar                           
light-overlay-7.0.1-forge.jar                    
durabilityviewer-1.19.1-forge42.0.1-1.10.jar     
skbackpacks-1.3.jar
BetterF3-4.0.0-Forge-1.19.2.jar                  
cloth-config-8.2.88-forge.jar                    
voicechat-forge-1.19.2-2.4.7.jar                 
appleskin-forge-mc1.19-2.4.2.jar                 
NoFog-1.3.2_1.19.2-forge.jar                     
createaddition-1.19.2-20230507a.jar

**Comment by PepperCode1** [comment]
All memory leaks in Flywheel have been fixed in 0.6.9. The rest of the leaks and the main cause of this issue are in Create.
