### ISSUE TITLE
1.20?

### ISSUE THREAD

**Issue by bswan** [Engine-Room/Flywheel#185]
Did anyone tried compiling that mod for 1.20? Are there devs workning on updating it? Should I go back to modding and try make 1.20 branch? 🤣

**Comment by rdrpenguin04** [comment]
Quote from Pepper on Discord: "To be honest the 1.19.3 branch is already good to go and porting from that to 1.20 will take the same amount of time as reviewing a port pull request"

**Comment by bswan** [comment]
Meaning what exacly? That Pepper would port it or that they wayting for someone to create pull request and then they would approve it and update mod so mods depending on it can update? If so I will give it a try tomorrow. I quite rusty in moding, last time I wrote anything for minecraft was back in beta times :D But quote makes me think it should be easy to do so I will try

**Comment by rdrpenguin04** [comment]
Pepper is going to port it and is already in the process of doing so.

**Comment by bswan** [comment]
Ok, thank you, looking forward to it 👍

**Comment by PepperCode1** [comment]
The port is now complete and stable.
