### ISSUE TITLE
Mod create requires flywheel 0.6.9 or above, and below 0.6.10 Currently, flywheel is 0.6.8.a

### ISSUE THREAD

**Issue by Artos003** [Engine-Room/Flywheel#192]
### Describe the Bug

While creating a server i ran into this issue. 

Mod create requires flywheel 0.6.9 or above, and below 0.6.10
		Currently, flywheel is 0.6.8.a
		
problem is, i cant find 0.6.9....
![image_2023-07-06_155451665](https://github.com/Jozufozu/Flywheel/assets/117882146/dc3a9df0-78df-420d-9a17-ae7f87b335e2)

### Reproduction Steps

1. launch
2. loads
3. crash
...

### Expected Result

the game to load

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3060

### Mod Version

0.6.8.a

### Minecraft Version

1.18.2

### Loader Version

Forge 40.2.4

### Other Mods

create

**Comment by RedstoneGyerek** [comment]
i just reported the same thing on create's page lol
