### ISSUE TITLE
Readme link to all flywheel versions is outdated

### ISSUE THREAD

**Issue by Requios** [Engine-Room/Flywheel#193]
### Describe the Bug

The README.md states "For a list of available Flywheel versions, you can check [the maven](https://maven.tterrag.com/com/jozufozu/flywheel/Flywheel-Forge/)."
This leads to versions up to 1.18, but there are 1.19 and 1.20 versions. I initially didn't find them, and almost assumed this mod wasn't updated anymore. But going up a folder reveals them. 

Could you update the link so it points to https://maven.tterrag.com/com/jozufozu/flywheel/ instead?

### Reproduction Steps

1. Go to the readme
2. Click on the link

### Expected Result

It shows all versions, including the most up to date ones

### Operating System

Irrelevant

### What is your GPU?

Irrelevant

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

Irrelevant

**Comment by PepperCode1** [comment]
Indeed, that link is outdated.

**Comment by PepperCode1** [comment]
This has been fixed in the latest commit.
