### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by saphsara** [Engine-Room/Flywheel#194]
### Describe the Bug

I am running 1.19.2 forge with create , i added flywheel and i am getting error that states
"Mod Creaate requires flywheel 0.6.9 or above , and below 0.6.10 Currently flywheel is 0.6.8a, " i went to see if there is a new version i cant seem to find it. 

### Reproduction Steps

1. removed flywheel and it works , 
2. reinstalled flywheel and no go
3.
4.
...
![Screenshot 2023-07-11 130727](https://github.com/Jozufozu/Flywheel/assets/33788318/3fb8e4df-a5c8-43ad-927e-2ad4f8e2d245)

### Expected Result

is there a newer version i am not seeing

### Operating System

windows 11

### What is your GPU?

na

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

43.2.10

**Comment by Cubichesky** [comment]
I faced the same problem
![изображение](https://github.com/Jozufozu/Flywheel/assets/66108320/e14f25fe-47bb-45a5-8dba-d4fe79489580)

**Comment by Catamonium** [comment]
Create comes packed with Flywheel, remove the separate file.
