### ISSUE TITLE
Create and flywheel verrsion above 0.6.10, below 0.6.11. Those doesn't exist/not available for download.

### ISSUE THREAD

**Issue by webtomek** [Engine-Room/Flywheel#201]
### Describe the Bug

1.19.2 forge, create: "create requires flywheel 0.6.10 or above, and below 0.6.11. Currently, flywheel is 0.6.8.a"

 

I'm looking and the download files and there's nothing above 1.19.2-0.6.8.a. Then how am I supposed to use it? 
https://www.curseforge.com/minecraft/mc-mods/flywheel/files

### Reproduction Steps

1.
2.
3.
...

### Expected Result

-

### Operating System

win10

### What is your GPU?

rtx 2060 but irrelevant

### Mod Version

0.6.10

### Minecraft Version

1.20.1

### Loader Version

43.2.11

**Comment by embeddedt** [comment]
Remove the separate Flywheel mod JAR, it's bundled with Create now.

**Comment by ADDED598** [comment]
> Remove the separate Flywheel mod JAR, it's bundled with Create now.

i did it. thank you for your issue!

**Comment by webtomek** [comment]
I didn't notice this issue is still here. It solved the problem, so I'll close it. Thanks for the answer too (a bit late to comment, but still)
