### ISSUE TITLE
Create requires a higher version of Flywheel, but there is no such version

### ISSUE THREAD

**Issue by michelle1574** [Engine-Room/Flywheel#205]
### Describe the Bug

Version required: 0.6.9
but the latest: 0.6.8.a
Please release the 0.6.9 version real quick!

### Reproduction Steps

No

### Expected Result

the start would start

### Screenshots and Videos

![image](https://github.com/Jozufozu/Flywheel/assets/70703680/d03a2019-857e-4389-b923-2d1c8c1ad6d9)

### Crash Report or Log

https://pastebin.com/LW1GHNzm

### Operating System

Windows 11

### What is your GPU?

Intel HD Graphics 620

### Mod Version

0.6.8

### Minecraft Version

1.19.2

### Loader Version

Forge 43.2.23

### Other Mods

![image](https://github.com/Jozufozu/Flywheel/assets/70703680/cca77109-490f-4155-b1e8-e9ecad0011da)
here ^

**Comment by Syntrace** [comment]
Delete the flywheel-forge-1.19.2-0.6.8 Mod, it is already embedded in create
