### ISSUE TITLE
Flywheel fails to load correctly 

### ISSUE THREAD

**Issue by Shredddder** [Engine-Room/Flywheel#212]
### Describe the Bug

When starting up a server that includes the create mod, the game starts up and takes me to a screen showing a flywheel error when there is no flywheel even installed.

### Reproduction Steps

1. Insert the zip file in prism launcher
2. press launch
3. Recieve error (100% on my end)
[Expedition_Enigma-1.0.zip](https://github.com/Jozufozu/Flywheel/files/13325962/Expedition_Enigma-1.0.zip)

...

### Expected Result

I expected to go to the minecraft menu so I could press play on the specific server.

### Screenshots and Videos

![image](https://github.com/Jozufozu/Flywheel/assets/121005468/f438e8cf-1d57-4808-90db-6697c512758f)

### Crash Report or Log

https://mclo.gs/DJDE9Ud

### Operating System

Windows 11

### What is your GPU?

CPU  	12th Gen Intel(R) Core(TM) i7-12700H 

### Mod Version

0.5.1

### Minecraft Version

1.18.2

### Loader Version

40.2.10

### Other Mods

[Expedition_Enigma-1.0.zip](https://github.com/Jozufozu/Flywheel/files/13325986/Expedition_Enigma-1.0.zip)

### Additional Context

The same issue happens if I use other modpacks that have create such as Life in the Village 3 for example.

**Comment by PepperCode1** [comment]
This is a Forge issue that does not have a fix right now and may never get a fix for 1.18.2.

**Comment by Shredddder** [comment]
> This is a Forge issue that does not have a fix right now and may never get a fix for 1.18.2.

Why is it that others can play on the modpack though? And Life in the Village 3 is on 1.19.2

**Comment by PepperCode1** [comment]
I do not know. The same issue is also present in all versions after 1.18.2.
