### ISSUE TITLE
Segmentation fault with Iris, Sodium, and Flywheel

### ISSUE THREAD

**Issue by birb7** [Engine-Room/Flywheel#217]
### Describe the Bug

upon loading into a server or world, i get a crash anywhere between instantly, after 5 minutes, or after 3 hours. ive made sure to update my drivers and have seen similar issues caused by flywheel, iris, and mesa drivers thats supposedly been fixed.
PS. it wont let me choose the proper minecraft version 1.20.1

### Reproduction Steps

1.enable shaders
2.join singleplayer or multiplayer game
3.crash

### Expected Result

the game to not crash.

### Crash Report or Log

https://pastebin.com/TLCazn6c

### Operating System

Linux Mint 21.2

### What is your GPU?

RX 6600XT

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

Fabric 0.14.25

**Comment by IThundxr** [comment]
The log doesnt exist, use something like https://mclo.gs/ please
