### ISSUE TITLE
flywheel makes Create: Dream & Desires not load

### ISSUE THREAD

**Issue by TheOnlyRamiro** [Engine-Room/Flywheel#218]
### Describe the Bug

:p

### Reproduction Steps

1. install mod
2. launch game
3. wait dat shit to load
4. boom loading error

### Expected Result

i expect this to be fixed ty

### Screenshots and Videos

![image](https://github.com/Jozufozu/Flywheel/assets/156981477/12417713-ccc7-4b18-a04c-b089b5c5b9fd)

### Crash Report or Log

https://pastebin.com/D450vWnf

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 750Ti

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

Forge 43.3.5

### Other Mods

idk

### Additional Context

idk

**Comment by IThundxr** [comment]
Dreams & Desires issues, either update it if there's a update or reach out to them in their discord

**Comment by Jozufozu** [comment]
Yeah this is a bug with Create DD
