### ISSUE TITLE
1.20.1 forge mod loading erros

### ISSUE THREAD

**Issue by Thunderrock424242** [Engine-Room/Flywheel#220]
### Describe the Bug

mod loading erros 

### Reproduction Steps

1. load flywheel with latest oculas version and create 
2.
3.
...

### Expected Result

not crash

### Screenshots and Videos

![Screenshot 2024-01-22 122537](https://github.com/Jozufozu/Flywheel/assets/119463825/5d122deb-8881-4638-aaec-f1a5c73c9b3f)
[latest.log](https://github.com/Jozufozu/Flywheel/files/14013467/latest.log)

### Operating System

windows 11

### What is your GPU?

rtx 4060

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

idk

**Comment by Kaloyan501** [comment]
Please provide a crash log, the loader version you are using and your full mod list.

**Comment by Kaloyan501** [comment]
Ok, sooo from what I am seeing, you installed flywheel for versions between 1.19.2 and 1.20, you current version is 1.20.1. That is greater than 1.20, soo update Flywheel is you can or downgrade your minecraft version. Also, If you are on Minecraft 1.20 and you downloaded the jar seperatly, don't do that. Create does not need the Flywheel jar anymore, it's bundled with the Create jar.

**Comment by Kaloyan501** [comment]
I saw that the separate jar was not avalible for download anymore, so disregard what I sayed above. Just downgrade your minecraft version to 1.20 or update the Create mod.

**Comment by IThundxr** [comment]
> I saw that the separate jar was not avalible for download anymore, so disregard what I sayed above. Just downgrade your minecraft version to 1.20 or update the Create mod.

No do not do that, get 1.20.1 create and remove flywheel from your mods folder
