### ISSUE TITLE
crash at neoforge

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Engine-Room/Flywheel#237]
[crash report](https://mclo.gs/ttjDF0S)

**Comment by IThundxr** [comment]
Iris Flywheel Compat is crashing ~ unrelated to flywheel itself

Report this to that mod's author

**Comment by Mr-Ao-Dragon** [comment]
i removed oculus
________________________________
发件人: IThundxr ***@***.***>
发送时间: 2024年5月5日 2:18
收件人: Jozufozu/Flywheel ***@***.***>
抄送: 敖律风 ***@***.***>; Author ***@***.***>
主题: Re: [Jozufozu/Flywheel] crash at neoforge (Issue #237)


Iris Flywheel Compat is crashing ~ unrelated to flywheel itself

Report this to that mod's author

―

**Comment by KuroiTengokuWeb** [comment]
Crash with oculus-mc1.20.1-1.7.0. Works with oculus-mc1.20.1-1.6.15a
