### ISSUE TITLE
Client-sided crash with Create and Quark

### ISSUE THREAD

**Issue by karltroid51** [Engine-Room/Flywheel#25]
Hi! I'm using this on my server and every once in a while I get a client crash. Trawling through the log, it says something about Quark, Create, and Flywheel. I'll attach the crash log below. Thank you in advance for any help!
[crash-2021-08-06_09.11.04-client.txt](https://github.com/Jozufozu/Flywheel/files/6942655/crash-2021-08-06_09.11.04-client.txt)

**Comment by Jozufozu** [comment]
This is fixed in the [latest version](https://www.curseforge.com/minecraft/mc-mods/flywheel/files) of Flywheel
