### ISSUE TITLE
Random and Mysterious "Unexpected error" crashes

### ISSUE THREAD

**Issue by Kapussi** [Engine-Room/Flywheel#26]
I've been having these mysterious crashes while playing in my mod pack, they're random and the crash reports always has flywheel and create. I would assume one of those two mods may be causing it. These are the 3 most recent crashes, but there's more, however they're all probably identical. The game has a habit of saving before crashing, so no progress were lost.

https://pastebin.com/aEQSrRGd
https://pastebin.com/iLPkHTJq
https://pastebin.com/1DA5f040

Please do help translate these reports for me, I'm curious to know why this is happening.

**Comment by Jozufozu** [comment]
Fixed in latest create/flywheel. Thanks for the report!
