### ISSUE TITLE
Flywheel mod and problem with Embeddium.

### ISSUE THREAD

**Issue by Graoth** [Engine-Room/Flywheel#260]
### Describe the Bug

Hello. I have a crash like in screenshoot below. The problem is that i cant upgrade embeddium to correct version. In time when that screenshoot was done THERE WAS NO embeddium mod file anywhere. When i install correct version - minecraft crashes with code 1 co its probably becouse of 2 the same mods. But i cant find this 0.3.19 version to delete it. Help please. 
Flywheel wersion is 0.6.11-13 on minecraft 1.20.1 with Forge 47.3.7

### Reproduction Steps

1.Everytime when minecraft lunched by CurseForge luncher on Better MC BMC4 v32.5 modpack.
2.
3.
...

### Expected Result

Find this stupid 0.3.19 file to delete it ....

### Screenshots and Videos

![11111](https://github.com/user-attachments/assets/26f4fd50-c075-4ac3-a9ec-c7563b257cd9)

### Crash Report or Log

https://pastebin.com/rCvxzAfv

### Operating System

Windows 10

### What is your GPU?

RTX 2070 Super

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

Forge 47.3.7

**Comment by PepperCode1** [comment]
Xenon provides Embeddium version 0.3.19. Replace Xenon with the latest version of Embeddium.
