### ISSUE TITLE
1.20.1 - EXCEPTION_ACCESS_VIOLATION when using Create & Oculus shaders

### ISSUE THREAD

**Issue by artman41** [Engine-Room/Flywheel#272]
### Describe the Bug

When using shaders, flywheel can crash with `EXCEPTION_ACCESS_VIOLATION` in the Render thread.

| Mod | Version |
|-|-|
|Create|1.20.1 0.5.1j |
|Flywheel|1.20.1 0.6.11-13 |
|Oculus|1.20.1 1.7.0 |
|Oculus Flywheel Compat|1.20.1 1.1.4 |

### Reproduction Steps

1. Launch a minecraft world using Oculus & Create
2. Place a Flywheel rendered block (like the crusher)
3. Enable shaders
4. Wait for the crash, sometimes instant, sometimes can take a while

### Expected Result

No crash

### Crash Report or Log

https://pastebin.com/dMuvvDQe

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce RTX 4090

### Mod Version

0.6.11-13

### Minecraft Version

1.20.1

### Loader Version

Forge 47.3.12

### Other Mods

| Mod | Version |
|-|-|
|Create|1.20.1 0.5.1j |
|Oculus|1.20.1 1.7.0 |
|Oculus Flywheel Compat|1.20.1 1.1.4 |

### Additional Context

[latest.log](https://github.com/user-attachments/files/17882229/latest.log)
[hs_err_pid19892.log](https://github.com/user-attachments/files/17882230/hs_err_pid19892.log)

**Comment by Jozufozu** [comment]
Not much we can do about this here. Please report this to the iris/flywheel compat dev
