### ISSUE TITLE
Crash after updating server/world

### ISSUE THREAD

**Issue by gilfort** [Engine-Room/Flywheel#29]
Hi, I just updated our server from create 3.1 to 3.2 and therefore installing flywheel in the process. 
The server runs without issues and SP also works fine when creating new worlds. 

If I try to connect to the server I'll get the following client-side crash: https://mcpaste.io/ad060e0bb8b184a0

It seems like some already existing create contraptions are causing the issue. 

Thanks!

p.s. I disabled Optifine to test this, but it didn't change anything :(

**Comment by Jozufozu** [comment]
Make sure you're using flywheel 0.2.3 and create 0.3.2d

**Comment by gilfort** [comment]
Thanks!
Upgrading Create to 0.3.2d fixed it. 
Curseforge defined the 0.3.2d version as "older" than the 0.3.2c version, which created the error while updating. 
(just as note if anyone else encounters this issue)
