### ISSUE TITLE
Flywheel 0.2.3 causing Create render issues with Sodium Reforged

### ISSUE THREAD

**Issue by oremilk** [Engine-Room/Flywheel#30]
The most recent Flywheel version with Create 0.3.2c is causing render issues (invisible cogs/shafts, or z-fighting vertices) with Sodium Reforged. It's only this version that causes these issues. 

Changing Sodium settings seems to fix the render issues until something updates the cogs/shafts, which then they turn invisible again. Moving structures are also invisible no matter what is done.

**Comment by emberquill** [comment]
Same issue here. Looks like reloading chunks with F3+A causes cogs/shafts/wheels/etc. to reappear (and that chunk reload is probably what's happening behind the scenes when you adjust your Sodium settings), but they disappear again whenever you leave the area and return.

It appears to be something to do with Flywheel's 0.2.3 update, because downgrading to Flywheel 0.2.2 and Create 0.3.2c fixed the issue for me.

**Comment by wchen1990** [comment]
The commit that causes the incompat is 931b4a33aefcce743baffad3b2feb10c5b8b589e.

I believe the main culprit is the change in where the `BeginFrameEvent` event is mixed in. As the point of the commit was to fix the incompat with Optifine, I'm not sure how this would be fixed for compatibility for both Optifine and Sodium Reforged. I personally use Sodium Reforged so I just made a custom one off branch for myself that changed the mixin injection point and using that for myself.

But, I imagine a wider audience uses Optifine + Shaders so I'm not sure if this would even be a priority for the developer.

**Comment by Jozufozu** [comment]
> The commit that causes the incompat is 931b4a3

Ah I had a feeling that might have been the issue. Thanks for the investigation! I'll see if I can come up with a solution that works for both.

**Comment by batydoo** [comment]
> The commit that causes the incompat is [931b4a3](https://github.com/Jozufozu/Flywheel/commit/931b4a33aefcce743baffad3b2feb10c5b8b589e).
> 
> I believe the main culprit is the change in where the `BeginFrameEvent` event is mixed in. As the point of the commit was to fix the incompat with Optifine, I'm not sure how this would be fixed for compatibility for both Optifine and Sodium Reforged. I personally use Sodium Reforged so I just made a custom one off branch for myself that changed the mixin injection point and using that for myself.
> 
> But, I imagine a wider audience uses Optifine + Shaders so I'm not sure if this would even be a priority for the developer.

would you be able to send me the short term fix?

**Comment by ghost** [comment]
A work around for this is changing the flywheel config or running the command /flywheel backend off
