### ISSUE TITLE
Client side crash while rendering areas (usually teleporting/respawning)

### ISSUE THREAD

**Issue by JadeiteSwan** [Engine-Room/Flywheel#32]
Game crashes when teleporting into unrendered areas.

First time noticed on 0.2.1, where the error could only be found in the crash log.
[crash-2021-08-15_16.45.00-client.txt](https://github.com/Jozufozu/Flywheel/files/6988261/crash-2021-08-15_16.45.00-client.txt)

On version 0.2.3, the launcher displays the error directly as:

Error: java.lang.NoSuchMethodError: 
com.jozufozu.flywheel.event.BeginFrameEvent.getStack()Lcom/mojang/blaze3d/matrix/MatrixStack;
Exit Code: -1

[crash-2021-08-15_17.03.31-client.txt](https://github.com/Jozufozu/Flywheel/files/6988264/crash-2021-08-15_17.03.31-client.txt)

**Comment by Jozufozu** [comment]
Update Create to 0.3.2d
