### ISSUE TITLE
Frequent Crashing on Render - Unreported Exception

### ISSUE THREAD

**Issue by ITCMD** [Engine-Room/Flywheel#34]
Frequent but seemingly random crashes from flywheel for all clients on the server.

[CRASH REPORT AND MOD LIST](https://paste.ee/p/4wHEW)

Starts on line 2156

**Comment by Jozufozu** [comment]
Fixed in Flywheel 0.2.3 and Create 0.3.2d.

**Comment by ITCMD** [comment]
Obliged, thought I was on latest.
