### ISSUE TITLE
java.lang.NoSuchMethodError: com.jozufozu.flywheel.event.BeginFrameEvent.getStack()Lcom/mojang/blaze3d/matrix/MatrixStack

### ISSUE THREAD

**Issue by raimkras97** [Engine-Room/Flywheel#37]
Client side crash moded server side is stable. 
When left clicking on Windmill Bearing + Sails + Sails Bearing instantly crashes
if there is a fix, that would be grate!
and is there a possibility that the crash is envolved from corrupt world?
crash repport
[crash-2021-08-26_20.59.11-client.txt](https://github.com/Jozufozu/Flywheel/files/7061868/crash-2021-08-26_20.59.11-client.txt)

**Comment by Jozufozu** [comment]
Update Create to 0.3.1d
