### ISSUE TITLE
Game crashing directly after loading in to a world

### ISSUE THREAD

**Issue by CanineData** [Engine-Room/Flywheel#40]
[crash-2021-09-13_16.50.59-client.txt](https://github.com/Jozufozu/Flywheel/files/7156015/crash-2021-09-13_16.50.59-client.txt)

**Comment by Jozufozu** [comment]
Updating to the [latest version of Create](https://www.curseforge.com/minecraft/mc-mods/create/files/3419412) will fix the issue
