### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by elganger** [Engine-Room/Flywheel#42]
The only mods in my folder are:
flywheel 1.16-0.2.4
create-mc1.16.5_v0.3.2d
Im running them on the regular minecraft launcher with 1.16.5 forge

So when I launch the game, it instantly crashes and puts this msg:
The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file flywheel-client.toml of type CLIENT for modid flywheel
Exit Code: -1

idk how to fix this

**Comment by TelepathicGrunt** [comment]
Have you tried deleting the config file from the config folder? by deleting the config file, it should recreate it automatically the next time you run the game and have default values.

**Comment by Jozufozu** [comment]
Deleting the config file will fix this.
