### ISSUE TITLE
Screen filling with random garbage while moving large create contraptions

### ISSUE THREAD

**Issue by james83325** [Engine-Room/Flywheel#45]
As the title says, when I move a large contraption on a server with create and flywheel, the screen fills with random rendering junk (https://prnt.sc/1vmten4 https://prnt.sc/1vmtgwa). I have not yet been able to try running it in singleplayer, but I will update this post when I do.

**Comment by TimCabbage** [comment]
https://github.com/Jozufozu/Flywheel/issues/59#issuecomment-994261688

You might try this build as it seems like it's a similar issue

**Comment by Jozufozu** [comment]
I doubt that will have fixed it. Contraption rendering takes a different path than block/entity rendering

**Comment by TimCabbage** [comment]
I had both issues - it broke for me (in the original ticket) for all chests as well as all the contraptions. With no chests but only contraptions I had the issue too. And Your build fixed both with the mods working flawlessly now :)

**Comment by Phil0L** [comment]
This Problem still occures in 0.5.1.
Any help is appreciated.
https://cdn.discordapp.com/attachments/818995244636438558/930641437249404928/2022-01-12_02.56.17.png
https://cdn.discordapp.com/attachments/818995244636438558/930641437870129152/2022-01-12_02.56.16.png

**Comment by TimCabbage** [comment]
Did you try the version from #59 ?
(If that fixed it but then 0.5.1 has a similar issue, it's probably something else?)

**Comment by james83325** [comment]
closing this issue because i am no longer able to recreate the bug in the latest version of the mod
