### ISSUE TITLE
Crash for 1.16.5

### ISSUE THREAD

**Issue by GreenPasta-1** [Engine-Room/Flywheel#46]
I've tried this with a couple of other mods, and I've also tried just using flywheel and it works both ways. Minecraft boots up and flywheel pops up in the mods folder with the rest of my mods, but once I add the create mod for the respective version of minecraft it crashes just as the bar fills on the first loading screen (the red one with the mojang logo). I tried removing flywheel and it says that it's necesary in order to run the create mod, so I've tried running different versions of both mods, and they just don't seem to work together at all. I've tried reinstalling both mods, but nothing seems to work, and help?

**Comment by Jozufozu** [comment]
If you upload the crash report to [pastebin](https://pastebin.com/) I can take a look
