### ISSUE TITLE
getChunk mixin causing memory leak

### ISSUE THREAD

**Issue by Epic428** [Engine-Room/Flywheel#47]
Per our conversation earlier today, making this issue for posterity and tracking.

https://cdn.discordapp.com/attachments/748363248377528452/901479987838877766/2021-10-23_12-07-39.mp4

One of my co-developers said yesterday he left for an exam and came back 2hrs later to his JVM crashed due to “out of memory” error. Upon investigation he found that flywheel has two mixins for getChunk and is creating millions of objects before being garbage collected adding upwards of ~500mb - 1gb to the memory usage. He removed create and flywheel from his dev instance and the objects stopped showing in the list. Testing an isolated instance yielded flywheel generating 500mb+ from the mixin alone

**Comment by Jozufozu** [comment]
Should be fixed in [0.2.5](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3535459)
