### ISSUE TITLE
Suggestion: forge menu config

### ISSUE THREAD

**Issue by ghost** [Engine-Room/Flywheel#48]
I would appreciate the feature being added to change the config files from the forge Mods menu, I know there are commands and a config file its just more simple to config this way thanks

![image](https://user-images.githubusercontent.com/82549089/141490423-4607c2b3-0b5e-497a-9229-a522634a6089.png)

**Comment by AzureDoom** [comment]
The Forge Config system is dead since Minecraft 1.13 @cpm9 they can't add anything that doesn't existing in modern Minecraft.
