### ISSUE TITLE
crash on pause 

### ISSUE THREAD

**Issue by blasksun** [Engine-Room/Flywheel#55]
game crashes upon pressing esc and making game pause. 
only sensible info in crash logs is :
`[09:48:02] [Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Illegal classload request for com.jozufozu.flywheel.mixin.PausedPartialTickAccessor. Mixin is defined in flywheel.mixins.json and cannot be referenced directly
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher onBeginFrame(Lcom/jozufozu/flywheel/event/BeginFrameEvent;)V
		2: ASM: class com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher beginFrame(Lcom/jozufozu/flywheel/event/BeginFrameEvent;)V
org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for com.jozufozu.flywheel.mixin.PausedPartialTickAccessor. Mixin is defined in flywheel.mixins.json and cannot be referenced directly`

forge 38.0.16

**Comment by jambox5** [comment]
seems the issue is present in any 'pausable' scenario. ie Journey map, too slow loading into the game map first time, etc... any scenario where it could be on hold across a game-tick rollover

**Comment by Jozufozu** [comment]
Moving discussion for this crash to #69
