### ISSUE TITLE
GlException: mapBufferRange(...) crash

### ISSUE THREAD

**Issue by MonkaMaczna** [Engine-Room/Flywheel#56]
When launching a world or joining to multiplayer on Forge 1.18-38.0.17 with Fluwheel 1.18-0.4.0 and Create mod 1.18-0.4 it crashes the game with an error: 

```
The game crashed whilst unexpected error
Error: com.jozufozu.flywheel.backend.gl.error.GlException: mapBufferRange(ARRAY_BUFFER, 0, 1472, 2)
Kod zakończenia: -1
```

**Comment by Jozufozu** [comment]
Fixed in [0.4.1](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3564677)
