### ISSUE TITLE
Chests (and many other block models) are broken

### ISSUE THREAD

**Issue by TimCabbage** [Engine-Room/Flywheel#59]
![obraz](https://user-images.githubusercontent.com/1681879/145638527-47164ecf-8495-4a47-b5de-9588590387dd.png)
Note the lack of bottoms and the weird textures in the corner.
This was ran in 1.18.0 and 1.18.1 with the same effects, as well as Forge 39.0.0 and 38.0.16 and 38.0.17

The only mods enabled are Forge and Flywheel.

Flywheel version is 0.4.0

EDIT: Does not happen with just Forge installed in any of the abovementioned versions but without Flywheel

**Comment by Jozufozu** [comment]
Could you post a screenshot with F3 open?

**Comment by TimCabbage** [comment]
![obraz](https://user-images.githubusercontent.com/1681879/145653209-25563b3e-b9e4-4a40-8ea0-ddab32bb1260.png)

There You go, 
I've also confirmed this to be an issue on three separate PCs

**Comment by Jozufozu** [comment]
This seems to be an issue with AMD GPUs, thank you!

**Comment by TimCabbage** [comment]
No problem!
I can test it for You further as I have five machines available, one intel+nvidia, rest are amd + amd with one having a high-end amd dedicated graphics card.
Tell me how I can help You there :)

**Comment by Jozufozu** [comment]
Once I have something for you to test I'll let you know!

**Comment by TimCabbage** [comment]
If you need help, point me in the right direction - which files I should look at and I'll try to set it up and debug.
I do programming for a living so might just work :D

**Comment by GobbleyDuck** [comment]
ah finally someone who is experiencing the same issue as me! that happens to all the items that can be opened or played with like cranks and dials

**Comment by Jozufozu** [comment]
[This build](https://archive.tterrag.com/jenkins/flywheel/forge/1.18/23/flywheel-forge-1.18-0.4.1.23.jar) should fix the issue.

**Comment by TimCabbage** [comment]
Just tested on one system, seems fixed, will let You know more once I get more machines testing.
Thanks!

**Comment by TimCabbage** [comment]
Works on multiple systems, thanks!
Unsure if You want to close this or make a PR for closing :D

**Comment by Jozufozu** [comment]
Fixed in [0.4.2-rc](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3568139)

**Comment by GobbleyDuck** [comment]
Thanks so much!
