### ISSUE TITLE
Flywheel requires too new of a forge version

### ISSUE THREAD

**Issue by NightWolf301** [Engine-Room/Flywheel#6]
so when I try to use all of the downloads it some how said the folder crash log and not on the right point what do I do?

**Comment by Jozufozu** [comment]
Could you upload the crash log to [Pastebin](https://pastebin.com/)?

**Comment by NightWolf301** [comment]
https://pastebin.com/yNPdjWXf

**Comment by Jozufozu** [comment]
Updating to the [latest forge version](https://files.minecraftforge.net/net/minecraftforge/forge/) should fix the crash.

**Comment by NightWolf301** [comment]
I can't go higher because some of the mods I have doesn't go high than
1.16.4 you need to the aternos to remove it because it doesn't work for
anybody else

**Comment by Jozufozu** [comment]
Ah, this isn't really a Flywheel issue, then. Though most mods that work on 1.16.4 should work on 1.16.5

**Comment by CoolCat467** [comment]
I've heard that optifine does some interesting things to minecraft's rendering code. Try doing it without optifine if you are still having problems.

**Comment by Aurumaker72** [comment]
This is due for a close as it is irrelevant to the mod
