### ISSUE TITLE
Flywheels crashes game with create mod

### ISSUE THREAD

**Issue by Mithandill** [Engine-Room/Flywheel#62]
[crash-2021-12-10_23.47.21-client.txt](https://github.com/Jozufozu/Flywheel/files/7695828/crash-2021-12-10_23.47.21-client.txt)
Game crashes when Create contraption is overstressed.

**Comment by Jozufozu** [comment]
Only when it's overstressed? This crash looks like #56 otherwise

**Comment by GreenPanda64** [comment]
> Only when it's overstressed? This crash looks like #56 otherwise

it seems to happen when its not overstressed as well

**Comment by Jozufozu** [comment]
Ah thanks for clarifying. Duplicate of #56
