### ISSUE TITLE
[Bug] 1.18.1 With Create mod: When adding portable item interface onto cart contraption, causes game crash + Contraption not visible

### ISSUE THREAD

**Issue by scoutmaster118** [Engine-Room/Flywheel#64]
I made a working cart contraption that worked but was not visible in the game but could still be interacted with, once i added the portable item interface to the cart contraption the game crashed. after trying to reload it the file it would load up then crash again.

May have been when using a Chest and a Item interface
or it may be whn using more then one chest/item interface, i get this crash message 

The game crashed whilst unexpected error
Error: com.jozufozu.flywheel.backend.gl.error.GlException: mapBufferRange(ARRAY_BUFFER, 0, 1472, 2)
Exit Code: -1

Crash Report:
[crash-2021-12-11_13.48.54-client.txt](https://github.com/Jozufozu/Flywheel/files/7697603/crash-2021-12-11_13.48.54-client.txt)

**Comment by Jozufozu** [comment]
Fixed in [0.4.1](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3564677)
