### ISSUE TITLE
Create Basin heavy mean tick time increase and causes sky light to be 0 when unloading chunk

### ISSUE THREAD

**Issue by UdoMorgenstern** [Engine-Room/Flywheel#67]
### Describe the Bug

mc 1.18.1
forge 39.0.0

only create and flywheel mods installed:
create-mc1.18.1_v0.4a.jar
flywheel-forge-1.18-0.4.1.jar

Placing a create basin and then teleporting away so the chunk gets unloaded increases the mean tick time from ~7ms to 50+ms
teleporting back to the location of the placed basin will normalize the mean tick time but the chunk in which the basin has been placed has a sky light level of 0

### Reproduction Steps

1. create a new world
2. check /forge tps ensure it has normalized (all loading/generating done)
3. teleport to a location away from spawn (eg 1000, 1000) that the location is generated
4. check /forge tps ensure it has normalized (all loading/generating done)
5. place a basin
6. teleport back to spawn location
7. check /forge tps, repeatedly - mean time will increase more and more, sometimes to over 50 
8. teleport back to you basin, mean time will normalize, but sky light may break

### Expected Result

- no mean time increase when unloading a chunk
- skylight should not break

### Screenshots and Videos

broken light
![2021-12-13_10 32 15](https://user-images.githubusercontent.com/90903255/145788508-a54783da-804e-40c9-bcb1-e44ea673e378.png)
broken light debug screen
![2021-12-13_10 35 27](https://user-images.githubusercontent.com/90903255/145788512-a29fa463-a0bc-4e52-a785-16ff557934d5.png)

### Operating System

windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.1

### Forge Version

39.0.0

### Other Mods

create-mc1.18.1_v0.4a.jar

### Additional Context

profiling started before teleporting away from chunk with basin
 - with my basic understanding it seems unloading causes the mean time issue 
[2021-12-13_10_37_35-test-1_18_1.zip](https://github.com/Jozufozu/Flywheel/files/7702731/2021-12-13_10_37_35-test-1_18_1.zip)

**Comment by UdoMorgenstern** [comment]
remark: pillaring up above the "flywheel light chunk" will fix the daylight
remark2: TPS issue may also be a forge / 1.18 issue as we discovered this even before using create/flywheel - but using the basin it was 100% reproducible

**Comment by Pewmaymen** [comment]
It looks like you have Simulation Distance set to 12. The default is 10.  I also have it changed, setting it to 16 to match View Distance, which I increase because 10 is way too short.  It wouldn't surprise me if having it changed from the default of 10 (you couldn't change it in 1.17 and earlier) causes this issue.

**Comment by UdoMorgenstern** [comment]
@Pewmaymen  
Simulation distance seem not affect the issue. Using same render as simulation distance, or other combinations still shows the issue. Increase of the render/simulation distance on servers may be a problem as it may struggle keeping up with the demand if several people online. So this is not a viable solution nor workaround.

**Validation Update:** 
used flywheel-forge-1.18-0.4.2-rc.jar in combination with unreleased create sha: 521102556a7bcefea6a988b305c3ef9d53b615cc
So far not able to reproduce the light issue (5/5 times tested), but the mean tick time increase is the same

**Comment by Pewmaymen** [comment]
I was wondering if leaving Simulation Distance at the default would still
show the issue. I find it odd that only a few people have seen this issue
when there are a lot of people using Create (and Flywheel by proxy) that
don’t report the issue.

**Comment by UdoMorgenstern** [comment]
Checked using:
Flywheel: https://github.com/Jozufozu/Flywheel/commit/3e8644c9881231e0ba5056c47ef03cb045f4e56c
Create: https://github.com/Creators-of-Create/Create/commit/9897666249bea89e17398d0d54cdfdad0867bdca

No Mean Tick Time issue
No Light Issue

Tested using singleplayer / multiplayer
