### ISSUE TITLE
My game crashes

### ISSUE THREAD

**Issue by TheRealConcept** [Engine-Room/Flywheel#7]
The mod does not work. When I try to open a world with create mod it crashes my game. Please fix quick

**Comment by Jozufozu** [comment]
Could you upload the crash log to [pastebin](https://pastebin.com)?

**Comment by TheRealConcept** [comment]
https://pastebin.com/S0ZTyGu6

**Comment by TheRealConcept** [comment]
thats whats in the "latest" document

**Comment by Jozufozu** [comment]
The paste you linked to is private

**Comment by TheRealConcept** [comment]
oh sorry i fixed it

**Comment by Jozufozu** [comment]
The log makes it look like worldedit is causing the crash. Can you load your world if you uninstall worldedit?

**Comment by TheRealConcept** [comment]
i will try

**Comment by TheRealConcept** [comment]
i am not home right now but when i come back ill try and message the results

**Comment by CoolCat467** [comment]
@TheRealConcept Any luck?
