### ISSUE TITLE
Occasional Crash when trying to join server

### ISSUE THREAD

**Issue by MrFuzzihead** [Engine-Room/Flywheel#71]
### Describe the Bug

Bug appears to happen only around 50% of attempts to log in to server. I run a server with flywheel and other mods, and every other time I try to log in to the server with my client the client crashes. The server continues to run just fine as far as I can tell.

### Reproduction Steps

1. Load game
2. Attempt to join server running same mods and forge (including Flywheel)
3. Crash (around 50% of the time)
...

### Expected Result

I expect to log in to my server without crashing

### Crash Report or Log

https://pastebin.com/kUzLXj3L

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 2060 Super

### Mod Version

0.2.5

### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Other Mods

Mixin
Adv Peripherals
AI Improvements
AppleSkin
Astral Sorcery
AttributeFix
AutoRegLib
Better Advancements
Biomes O Plenty
Blur
Botania
BPeripherals
CBMultipart
CC Tweaked
Chocolate
Clumps
CodeChicken Lib
Collective
Comforts
Configured
CTM
Controlling
CraftTweaker
Create
Curios API
Digital Items
Ding
Dynamic View distance
DymanicSurrounding
Entity Culling
Fast Workbench
Fast Furnace
Fast Leaf Decay
Ferrite Core
Fish Traps
Harvest
Hidden Recipe Book
Inv Tweaks
Iron Chests
JEI Integ
JEI Tweaker
Journeymap
Just a Raft mod
JEI
JER
Macaws Bridges
Morph o tool
morpheus
NBT Periph
OAuth
ObserverLib
Optifine
Optiforge
overworld 2
patchouli
performant
placebo
projectred
random patches
reliquary
scorge
serene seasons
smooth boot
sound filters
spark
spice of life carrot
storage drawers
terraforged
timber
toast control
wandering trader
water strainer
yungs API
yungs etc...

**Comment by Charismara** [comment]
Same problem here with

Mod Version: 0.5.1
Minecraft Version: 1.18.1
Forge Version 39.0.18
Crash: https://mcpaste.io/ce528bc857bf3e61

Edit:
Same Crash happens on single player: https://mcpaste.io/d4364ad0612d56f4

**Comment by MrFuzzihead** [comment]
closing as this seems to be dead
