### ISSUE TITLE
Flywheel craches

### ISSUE THREAD

**Issue by zaze06** [Engine-Room/Flywheel#72]
### Describe the Bug

Game cant boot. When flywheel is setting up its shaders

### Reproduction Steps

1. use forge 39.0.5 for 1.18.1
2. add flywheel to the mods
3. run the game

### Expected Result

The game to boot

### Crash Report or Log

https://gist.github.com/zaze06/de1a78f85e34c212e3207516ca9af489

### Operating System

Ubuntu 20.04

### What is your GPU?

AMD A8-5500 APU

### Mod Version

0.4.2-rc

### Minecraft Version

1.18.1

### Forge Version

39.0.5

### Other Mods

﻿<ul>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/refined-storage">Refined Storage (by raoulvdberge)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/light-overlay">Light Overlay (Rift/Forge/Fabric) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/extra-disks">Extra Disks (by MelanX)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/architectury-forge">Architectury API (Forge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/refined-storage-addons">Refined Storage Addons (by raoulvdberge)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2">Applied Energistics 2 (by AlgorithmX2)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/appleskin">AppleSkin (by squeek502)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/electrodynamics">Electrodynamics (by aurilisdev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/industrial-reborn">Industrial Reborn (by Maciej916)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-advancements">Better Advancements (by way2muchnoise)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/configured">Configured (by MrCrayfish)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge">Inventory HUD+ (by dmitrylovin)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/silent-gear">Silent Gear (by SilentChaos512)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/corail-tombstone">Corail Tombstone (by Corail_31)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod">MrCrayfish's Furniture Mod (by MrCrayfish)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer">Just Enough Resources (JER) (by way2muchnoise)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep">Just Enough Professions (JEP) (by Mrbysco)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei">Just Enough Items (JEI) (by mezz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/flywheel">Flywheel (by jozufozu)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions">Enchantment Descriptions (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap">Xaero's Minimap (by xaero96)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jasm">just another speedometer mod (jasm) (by AlienFromDia)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create">Create (by simibubi)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge">Cloth Config API (Forge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/silent-lib">Silent Lib (silentlib) (by SilentChaos512)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks">Mouse Tweaks (by YaLTeR)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/extrastorage">ExtraStorage (by 3divad99)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cc-tweaked">CC: Tweaked (by SquidDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map">Xaero's World Map (by xaero96)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod">MrCrayfish's Gun Mod (by MrCrayfish)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/framework">Framework (by MrCrayfish)</a></li>
</ul>

**Comment by zaze06** [comment]
note. it started on macOS, unsure of windows

**Comment by Jozufozu** [comment]
Fixed in latest versions of [Create](https://www.curseforge.com/minecraft/mc-mods/create/files/3583784) and [Flywheel](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3584224).
