### ISSUE TITLE
Crashing when launching with custom launcher

### ISSUE THREAD

**Issue by PavlychevV** [Engine-Room/Flywheel#73]
Hello. 

I'm trying to install Flywheel with Create on Minecraft 1.18.1 on macOS M1
The reason I use custom launcher is because it supports custom java and this java is optimised for ARM (M1)
But every time I launch with Forge 39.0.0 and Flywheel 0.4.2-rc it crashes, but on mojang's launcher it doesn't. I want to use custom launcher cuz it doesn't have such performance and energy impact as original. 

Here's log

https://paste.ee/p/ZCiOL

Launcher: MultiMC, java zulu-17, installed via this tutorial https://www.youtube.com/watch?v=bb-laqqlHWg

**Comment by whittheperson** [comment]
I have the same issue. It's just Flywheel, and create alone doesn't cause any issues. (other than needing flywheel; it still launches)

**Comment by Jozufozu** [comment]
Sorry to hear, but this is the wrong place. I can't help you, but it looks to me like the launcher isn't correctly loading lwjgl. Can you even run an unmodded instance through it?
