### ISSUE TITLE
class loading error when enchantment descriptions mod added

### ISSUE THREAD

**Issue by IamSweetie** [Engine-Room/Flywheel#76]
### Describe the Bug

I added the file EnchantmentDescriptions-Forge-1.17.1-8.17.1.jar to my current modpack which had previously loaded with no errors and it had class loading errors on startup - poss a problem with compatibility with Flywheel mod - I've also logged the issue on their github

### Reproduction Steps

1.add EnchantmentDescriptions-Forge-1.17.1-8.17.1.jar along with flywheel to mods folder
2.load up minecraft
3. get classloading error 
...
[crash-2021-12-22_20.51.29-fml.txt](https://github.com/Jozufozu/Flywheel/files/7770952/crash-2021-12-22_20.51.29-fml.txt)

### Expected Result

I hoped to open Minecraft and play ;)

### Crash Report or Log

https://pastebin.com/zGEwCd1p

### Operating System

Windows 10

### What is your GPU?

AMD Radeon HD 7800 Series

### Mod Version

0.3.0

### Minecraft Version

1.17.1

### Forge Version

37.1.0

### Other Mods

see crashlog

**Comment by Jozufozu** [comment]
Crash log has nothing to do with Flywheel. Seems like Enchantment Descriptions was compiled against Java 17 instead of 16.
https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/92
