### ISSUE TITLE
1.18.1 crash after world load

### ISSUE THREAD

**Issue by GlueStue** [Engine-Room/Flywheel#80]
### Describe the Bug

in 1.18.1 the game crashes after world load. There are a few seconds to move around but then an immediate crash.

### Reproduction Steps

Create a modpack with create and flywheel. Launch the game and create a world. It

### Expected Result

I expected the game to load

### Crash Report or Log

https://pastebin.com/ujtWQnfU

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GT 730

### Mod Version

0.5.0

### Minecraft Version

1.18.1

### Forge Version

39.0.9

**Comment by DizzyPrime** [comment]
Also receiving this bug, tested both with other mods and with nothing but Create, Flywheel, and JEI on the newest forge version

EDIT: here's my pastebin crash report to keep this in one place https://pastebin.com/qjsW0YTY

GPU is Gigabyte Geforce RTX 3080

**Comment by AeiouEnigma** [comment]
@Jozufozu in my testing this bug can be consistently reproduced by loading a world after disabling Flywheel backend.

Actually, my crash is a separate one. I'll make a new issue for it.

**Comment by LegendaryTot** [comment]
I get same error w/ similar mod setup (using GTX 970). I noticed a few things:

- Creating superflat world does not immediately crash. It crashes as soon as I place down a chest.
- Creating a new world does not immediately crash depending on the chunks you spawn in. Flying towards a village it immediately crashes.

**Comment by DizzyPrime** [comment]
So if the game loads a chest it crashes. 

>

**Comment by DizzyPrime** [comment]
> I get same error w/ similar mod setup (using GTX 970). I noticed a few things:
> 
>     * Creating superflat world does not immediately crash. It crashes as soon as I place down a chest.
> 
>     * Creating a new world does not immediately crash depending on the chunks you spawn in. Flying towards a village it immediately crashes.

So if the game loads a Chest or storage container it crashes. Neat.

**Comment by sshcrack** [comment]
Bump

**Comment by Jozufozu** [comment]
Should be fixed in [0.5.0a](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3584224)
