### ISSUE TITLE
[1.18.1] FlyWheel Causing Crash, Preventing World Load

### ISSUE THREAD

**Issue by oitsjustjose** [Engine-Room/Flywheel#82]
### Describe the Bug

When placing down any Create blocks (in my specific case, a Windmill bearing) my client crashes to desktop. I have tried all three Flywheel backend settings (`batched`, `instancing` and `off`) and the crash still occurs.

[Full log (`debug.log`)](https://github.com/Jozufozu/Flywheel/files/7791319/debug.log)

### Reproduction Steps

1. Place down a windmill bearing
2. ✨ Crash ✨

### Expected Result

To be able to not crash at least if flywheel's backend is off.

### Screenshots and Videos

[Video Proof in Singleplayer](https://oitsjustjose-sharex.s3.us-east-2.amazonaws.com/2021/12/12-29-21%2021-02-33-011.mp4)

### Crash Report or Log

[crash-2021-12-30_02.48.14-client.txt](https://github.com/Jozufozu/Flywheel/files/7791318/crash-2021-12-30_02.48.14-client.txt)

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3080

### Mod Version

0.5.0

### Minecraft Version

1.18.1

### Forge Version

39.0.9

### Other Mods

<details>
  <summary>Full Mod List </summary>
<pre>
globaldataandresourcepacks-1.18-1.10.2.jar
Snow!RealMagic!-1.18-forge-3.0.1.jar
absentbydesign-1.18-1.6.0.jar
Adorn-3.1.0+1.18.1-forge.jar
AI-Improvements-1.18-0.4.0.jar
alexsmobs-1.15.1.jar
AmbientEnvironment-forge-1.18.1-7.0.3.jar
appleskin-forge-mc1.18-2.2.0.jar
Aquaculture-1.18.1-2.3.2.jar
architectury-3.3.5.jar
artifacts-1.18.1-4.0.2.jar
assemblylinemachines-1.18-1.3.3.jar
AttributeFix-Forge-1.18.1-13.0.3.jar
AutoRegLib-1.7-52.jar
balm-2.3.1+0.jar
baubley-heart-canisters-1.18-1.0.0.jar
BetterCrates-1.18.1-1.0.0.jar
BetterThanMending-1.7.1.jar
bigbrain-1.4.0.jar
biomeinfo-1.18-1.3.1.jar
BowInfinityFix-1.18.x-rv11.jar
buildinggadgets-3.10.1-build.3+mc1.18.jar
cc-tweaked-1.18.1-1.100.0.jar
charginggadgets-1.5.0.jar
chipped-1.18.1-1.2.0.1-forge.jar
chunkloaders-1.1.7b-mc1.18.jar
citadel-1.10.7-1.18.jar
cloth-config-6.1.48-forge.jar
Clumps-forge-1.18.1-8.0.4.jar
collective-1.18.1-3.8.jar
comforts-forge-1.18-5.0.0.1.jar
configured-1.5.1-1.18.1.jar
connectedglass-1.1.1-mc1.18.jar
Controlling-forge-1.18.1-9.0.7.jar
cookingforblockheads-forge-1.18-11.0.0.jar
corail_woodcutter-1.18-2.2.0.jar
corpse-1.18.1-1.0.0.jar
CosmeticArmorReworked-1.18.1-v1.jar
CraftingAutomat-MC1.18.1-1.2.2.jar
create-mc1.18.1_v0.4b.jar
createchunkloading-0.3.1.jar
CreativeCore_v2.4.1_mc1.18.1.jar
curios-forge-1.18.1-5.0.4.2.jar
customizableelytra-1.18-1.6.3.jar
cyclepaintings_1.18.1-2.2.jar
DoggyTalents-1.18.1-2.4.0.jar
DrawersTooltip-1.18-forge-4.0.0.jar
DungeonCrawl-1.18.1-2.3.6.jar
effective_for_forge-1.001.jar
enderchests-1.18-1.9.0.jar
endertanks-1.18-1.11.0.jar
entangled-1.3.10-mc1.18.jar
EquipmentCompare-1.18.1-1.2.9.jar
expandability-5.0.0-forge.jar
expandedstorage-7.3.4+1.18.jar
ExtraDisks-1.18.1-2.0.2.jar
ExtraStorage-1.18.1-2.0.0.jar
extremeSoundMuffler-3.19_1.18.jar
FarmersDelight-1.18.1-1.0.0.jar
FastWorkbench-1.18.1-6.0.0.jar
flatbedrock-1.4.0-build.6+mc1.18.1.jar
FluidSystem-1.18.1-2.0.0.jar
flywheel-forge-1.18-0.5.0a.jar
functionalstorage-1.18.1-0.0.3.jar
furniture-7.0.0-pre27-1.18.1.jar
geckolib-1.18-forge-3.0.3.jar
glassential-forge-1.18-1.2.1.jar
globalxp-1.18.1-1.9.1.jar
guardvillagers-1.18.1.4.0.jar
hexerei-0.1.10.jar
Iceberg-1.18.1-1.0.31.jar
ImmersiveEngineering-1.18.1-7.0.1-144.jar
inventorysorter-1.18-19.0.0.jar
ItemBorders-1.18.1-1.1.5.jar
itemcollectors-1.1.3-mc1.18.jar
ItemPhysic_v1.4.20_mc1.18.1.jar
Jade-1.18-4.1.0.jar
jei-1.18.1-9.1.1.48.jar
Kiwi-1.18-forge-5.2.3.jar
kleeslabs-forge-1.18-11.0.0.jar
kotlinforforge-3.1.0-obf.jar
LibX-1.18.1-3.1.2.jar
light-overlay-6.0.4-forge.jar
lootr-1.18-0.0.12.35.jar
malum-1.18.1-1.1.1.jar
mcw-lights-1.0.2-mc1.18.1.jar
mininggadgets-1.10.2.jar
modular-routers-1.18.1-9.0.1-79.jar
morevillagers-FORGE-1.18.1-3.1.0.jar
MouseTweaks-forge-mc1.18-2.21.jar
movingelevators-1.2.34a-mc1.18.jar
mutil-1.18.1-4.0.0.jar
MyServerIsCompatible-1.18-1.0.jar
NaturesAura-35.3.jar
netherportalfix-forge-1.18-9.0.0.jar
ninjaphenix-container-library-1.2.8+1.18.jar
oauth-1.1.5-1.18.1.jar
occultism-1.18.1-1.23.8-release.jar
out_of_sight-1.18.1-1.0.1.jar
PassableFoliage-1.18-forge-3.0.0.jar
Patchouli-1.18.1-63.jar
pipez-1.18.1-1.0.1.jar
Placebo-1.18.1-6.0.2.jar
polymorph-forge-1.18.1-0.33.jar
PrettyPipes-1.10.4.jar
Quark-3.0-334.jar
rangedpumps-0.9.0.jar
RapidLeafDecay-1.18.1-2.0.0.jar
refinedstorage-1.10.0-beta.3.jar
refinedstorageaddons-0.8.0.jar
repurposed_structures_forge-4.0.9+1.18.1.jar
RootsClassic-1.18-1.1.16.jar
RSInfinityBooster-1.18.1-2.0+5.jar
sapience-1.18.1-1.0.1.jar
scannable-1.18.1-forge-1.7.6+da03abb.jar
selene-1.18-1.11.jar
shetiphiancore-1.18-3.10.0.jar
silent-gear-1.18.1-2.8.2.jar
silent-lib-1.18-6.0.0.jar
simplylight-1.18.1-1.4.0-build.26.jar
snowundertrees-1.18-1.1.5.jar
sophisticatedbackpacks-1.18.1-3.14.3.485.jar
starlight-1.0.0+forge.4fd2e63.jar
StorageDrawers-1.18.1-10.0.1.jar
supermartijn642configlib-1.0.9-mc1.18.jar
supermartijn642corelib-1.0.15a-mc1.18.jar
supplementaries-1.18.1-1.1.3.jar
tesseract-1.0.24-mc1.18.jar
tetra-1.18.1-4.1.2.jar
time-in-a-bottle-2.1.0-mc1.18.1.jar
timeout_fixes-1.18.1-1.0.0.jar
tinyredstone-1.18-3.1.0.jar
titanium-1.18-3.4.0-27.jar
ToastControl-1.18.1-6.0.0.jar
ToolBelt-1.18-1.18.0.jar
torchmaster-18.0.2-beta.jar
torchslabmod-1.18.1_v1.7.2.jar
trashcans-1.0.11-mc1.18.jar
trashslot-forge-1.18-11.0.0.jar
TravelAnchors-1.18.1-3.2.jar
travellersboots-1.18-1.6.0.jar
tuffdepth-1.18.1-1.2.0.jar
villagernames_1.18.1-3.5.jar
villagespawnpoint_1.18.1-1.9.jar
VTweaks-1.18-3.5.4.jar
waystones-forge-1.18.1-9.0.1.jar
windowlogging-mc1.18.1_v0.0.8.jar
wormhole-1.1.9-mc1.18.jar
Xaeros_Minimap_21.22.6_Forge_1.18.jar
XaerosWorldMap_1.18.9_Forge_1.18.jar
<pre>
</details>

### Additional Context

Running on a dedicated server host via Docker - this _shouldn't_ matter, but in case it does.

**Comment by Jozufozu** [comment]
Seems to be an incompatibility with starlight. Should be fixed with this PR https://github.com/PaperMC/Starlight/pull/111

**Comment by oitsjustjose** [comment]
Oh that makes sense, let me retest without it and I'll report back.

**Comment by AeiouEnigma** [comment]
[Definitely not a link to a build of Starlight that works with Create for you to use while waiting for that PR to be merged](https://github.com/AeiouEnigma/Starlight/releases/tag/create_compatibility)

**Comment by oitsjustjose** [comment]
Confirmed, removing Starlight to test works just fine on the latest build. Thanks @AeiouEnigma for the link, might try that out but for the sake of a public modpack I'd prefer just remove it for the time being ❤️
