### ISSUE TITLE
Crash at launch after updating to 0.5.0a

### ISSUE THREAD

**Issue by StrangeThistle** [Engine-Room/Flywheel#84]
### Describe the Bug

custom pack crashes at launch after updating to 0.5.0a (mc1.18.1). Game will run when reverting to 0.4.2-rc.

### Reproduction Steps

1. Update Flywheel and Create to latest versions. (Curse launcher)
2. Click play to open the Minecraft launcher
3. Click play to run the Minecraft instance.
4. Crash
...

### Expected Result

expect to load to Minecraft game menu

### Crash Report or Log

https://pastebin.com/2pwKXgbm

### Operating System

MacOS 12.0.1

### What is your GPU?

AMD Radeon R9 M390 2 GB

### Mod Version

0.5.0

### Minecraft Version

1.18.1

### Forge Version

39.0.9

### Other Mods

87 mods in pack, please see crash report. Supplementaries seems to be prominent in the crash report.

**Comment by Jozufozu** [comment]
Should be fixed by updating supplementaries
