### ISSUE TITLE
Game crashes whenever a Create contraption is moving

### ISSUE THREAD

**Issue by DukeBirdie** [Engine-Room/Flywheel#86]
My friend has this issue, he's running the game on windows. We were running it on a server and whenever I start using a create moving part, his game crashes but my game remains running. Here is the error that he gets when the game crashes:
![Screenshot_2021-12-31_023953](https://user-images.githubusercontent.com/61762313/147819413-83e777f8-f3ee-42d8-a723-32dddd4f3466.png)

**Comment by Jozufozu** [comment]
Fixed in latest [Create](https://www.curseforge.com/minecraft/mc-mods/create/files/3600402) and [Flywheel](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3600401).
