### ISSUE TITLE
Client crash on server login

### ISSUE THREAD

**Issue by faeldray** [Engine-Room/Flywheel#9]
I'm running a server with a modpack I made on it and I recently updated Create, which meant adding in Flywheel as well. I was able to log into the server without issue but my friend kept crashing every time he joined. I eventually had to remove Flywheel and downgrade Create just so he would stop crashing.

This is one of the crash reports he sent me: https://gist.github.com/faeldray/d06b2cba8ea6630c61bfba2cd3297151

**Comment by 34638a** [comment]
#22 Patch issued that should fix the issue (hopefully)
